import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.about': 'Về chúng tôi',
    'nav.features': 'Tính năng',
    'nav.caseStudies': 'Nghiên cứu trường hợp',
    'nav.pricing': 'Bảng giá',
    'nav.contact': 'Liên hệ',
    'nav.getDemo': 'Xem Demo',
    'nav.contactUs': 'Liên hệ với chúng tôi',
    
    // Home Page
    'home.hero.title': 'Tăng cường',
    'home.hero.subtitle': 'tương tác với khách hàng',
    'home.hero.subtitle2': 'bằng',
    'home.hero.subtitle3': 'Chatbot AI',
    'home.hero.description': 'Chuyển đổi hỗ trợ khách hàng thành động lực tăng doanh thu.\nTriển khai chatbot thông minh tương tác, chuyển đổi và làm hài lòng khách hàng 24/7.',
    'home.hero.getDemo': 'Xem Demo Miễn Phí',
    'home.hero.learnMore': 'Tìm hiểu thêm',
    
    // Why D2 Group
    'home.why.title': 'Tại sao chọn',
    'home.why.subtitle': 'Chúng tôi kết hợp công nghệ AI tiên tiến với chuyên môn kinh doanh sâu rộng để cung cấp chatbot thực sự hiểu khách hàng của bạn',
    'home.why.ai.title': 'Trí tuệ AI',
    'home.why.ai.desc': 'Xử lý ngôn ngữ tự nhiên tiên tiến hiểu ngữ cảnh và ý định',
    'home.why.security.title': 'Bảo mật Doanh nghiệp',
    'home.why.security.desc': 'Mã hóa cấp ngân hàng và tuân thủ các tiêu chuẩn bảo mật toàn cầu',
    'home.why.results.title': 'Kết quả Đã được Chứng minh',
    'home.why.results.desc': 'Trung bình tăng 40% chuyển đổi và giảm 60% chi phí hỗ trợ',
    'home.why.learnMore': 'Tìm hiểu thêm về chúng tôi',
    
    // Key Features
    'home.features.title': 'Tính năng',
    'home.features.subtitle': 'Mọi thứ bạn cần để tự động hóa và nâng cao cuộc trò chuyện với khách hàng',
    'home.features.smart.title': 'Cuộc trò chuyện thông minh',
    'home.features.smart.desc': 'Đối thoại tự nhiên như con người',
    'home.features.instant.title': 'Thiết lập tức thì',
    'home.features.instant.desc': 'Triển khai trong vòng 5 phút',
    'home.features.analytics.title': 'Phân tích thời gian thực',
    'home.features.analytics.desc': 'Theo dõi hiệu suất và tối ưu hóa',
    'home.features.multichannel.title': 'Đa kênh',
    'home.features.multichannel.desc': 'Website, WhatsApp, Facebook',
    'home.features.viewAll': 'Xem tất cả tính năng',
    
    // How It Works
    'home.howItWorks.title': 'Cách thức',
    'home.howItWorks.subtitle': 'Khởi động và vận hành trong 3 bước đơn giản',
    'home.howItWorks.step1.title': 'Kết nối dữ liệu của bạn',
    'home.howItWorks.step1.desc': 'Tải lên FAQ, thông tin sản phẩm và cơ sở kiến thức của bạn',
    'home.howItWorks.step2.title': 'Đào tạo Bot của bạn',
    'home.howItWorks.step2.desc': 'AI học hỏi doanh nghiệp và mô hình khách hàng của bạn',
    'home.howItWorks.step3.title': 'Triển khai & Mở rộng',
    'home.howItWorks.step3.desc': 'Khởi chạy trên các kênh và xem chuyển đổi tăng trưởng',
    
    // Use Cases
    'home.useCases.title': 'Kết quả',
    'home.useCases.subtitle': 'Xem cách các doanh nghiệp như bạn đang thắng lợi với chatbot AI',
    'home.useCases.ecommerce': 'Thương mại điện tử',
    'home.useCases.healthcare': 'Chăm sóc sức khỏe',
    'home.useCases.education': 'Giáo dục',
    'home.useCases.banking': 'Ngân hàng',
    'home.useCases.realestate': 'Bất động sản',
    'home.useCases.travel': 'Du lịch',
    'home.useCases.viewCaseStudies': 'Xem nghiên cứu trường hợp',
    
    // Testimonials
    'home.testimonials.title': 'Khách hàng',
    'home.testimonials.subtitle': 'Tham gia cùng 500+ doanh nghiệp đã chuyển đổi trải nghiệm khách hàng',
    'home.testimonials.1.content': 'Chatbot của D2 Group đã tăng chuyển đổi khách hàng tiềm năng của chúng tôi 45% chỉ trong 3 tháng. AI thực sự hiểu khách hàng của chúng tôi.',
    'home.testimonials.2.content': 'Tự động hóa hỗ trợ khách hàng 24/7 đã cách mạng hóa chất lượng dịch vụ của chúng tôi. Khách hàng yêu thích phản hồi tức thì.',
    'home.testimonials.3.content': 'Việc triển khai diễn ra suôn sẻ và ROI có thể thấy được trong vài tuần. Điểm hài lòng của sinh viên đạt mức cao nhất từ trước đến nay.',
    
    // Partners
    'home.partners.title': 'Được tin tưởng bởi',
    'home.partners.subtitle': 'Tham gia cùng những nhà lãnh đạo ngành này đã triển khai giải pháp của chúng tôi',
    
    // Home Pricing
    'home.pricing.title': 'Bảng giá',
    'home.pricing.subtitle': 'Chọn gói phù hợp với nhu cầu doanh nghiệp của bạn',
    'home.pricing.seeFullPricing': 'Xem bảng giá đầy đủ',
    
    // FAQ
    'home.faq.title': 'Câu hỏi',
    'home.faq.subtitle': 'Câu trả lời nhanh cho những câu hỏi thường gặp',
    'home.faq.q1': 'Chúng tôi có thể triển khai chatbot nhanh như thế nào?',
    'home.faq.a1': 'Hầu hết khách hàng đều hoạt động trong vòng 24-48 giờ. Thiết lập cơ bản chỉ mất 5 phút.',
    'home.faq.q2': 'Có tích hợp với CRM hiện tại của chúng tôi không?',
    'home.faq.a2': 'Có, chúng tôi tích hợp với hơn 50 nền tảng bao gồm Salesforce, HubSpot và API tùy chỉnh.',
    'home.faq.q3': 'ROI dự kiến là bao nhiêu?',
    'home.faq.a3': 'Khách hàng thường thấy ROI 3-5 lần trong vòng 6 tháng thông qua tăng chuyển đổi và giảm chi phí hỗ trợ.',
    'home.faq.viewFullFaq': 'Xem FAQ đầy đủ',
    
    // Final CTA
    'home.finalCta.title': 'Sẵn sàng',
    'home.finalCta.title2': 'Tự động hóa',
    'home.finalCta.title3': 'Cuộc trò chuyện khách hàng của bạn?',
    'home.finalCta.description': 'Tham gia cùng hàng trăm doanh nghiệp đã chuyển đổi trải nghiệm khách hàng với chatbot AI của D2 Group. Bắt đầu dùng thử miễn phí ngay hôm nay và xem kết quả trong vòng 48 giờ.',
    'home.finalCta.startTrial': 'Bắt đầu dùng thử miễn phí',
    'home.finalCta.bookDemo': 'Đặt lịch Demo',
    'home.finalCta.freeTrial': 'Dùng thử 14 ngày miễn phí',
    'home.finalCta.noCreditCard': 'Không cần thẻ tín dụng',
    'home.finalCta.setupIn5': 'Thiết lập trong 5 phút',

    // Features Page
    'features.hero.title': 'Tính năng',
    'features.hero.titleHighlight': 'mạnh mẽ',
    'features.hero.titleEnd': 'mang lại kết quả',
    'features.hero.description': 'Khám phá bộ công cụ AI toàn diện được thiết kế để chuyển đổi giao tiếp khách hàng và thúc đẩy tăng trưởng kinh doanh đo lường được.',
    'features.hero.cta': 'Xem tính năng hoạt động',

    // Core Features
    'features.core.title': 'Khả năng',
    'features.core.titleHighlight': 'cốt lõi',
    'features.core.subtitle': 'Mọi thứ bạn cần để mang lại trải nghiệm khách hàng xuất sắc',

    'features.core.nlp.title': 'Xử lý ngôn ngữ tự nhiên',
    'features.core.nlp.desc': 'AI tiên tiến hiểu ngữ cảnh, ý định và cảm xúc',
    'features.core.nlp.detail1': 'Hỗ trợ đa ngôn ngữ với độ chính xác 95%+',
    'features.core.nlp.detail2': 'Quản lý luồng hội thoại theo ngữ cảnh',
    'features.core.nlp.detail3': 'Phân tích cảm xúc và phát hiện emotion',
    'features.core.nlp.detail4': 'Nhận dạng ý định và trích xuất thực thể',

    'features.core.multiChannel.title': 'Triển khai đa kênh',
    'features.core.multiChannel.desc': 'Triển khai trên website, WhatsApp, Facebook và nhiều kênh khác',
    'features.core.multiChannel.detail1': 'Widget chat website với UI tùy chỉnh',
    'features.core.multiChannel.detail2': 'Tích hợp WhatsApp Business API',
    'features.core.multiChannel.detail3': 'Kết nối Facebook Messenger',
    'features.core.multiChannel.detail4': 'Hỗ trợ kênh SMS và voice',

    'features.core.realTime.title': 'Phân tích thời gian thực',
    'features.core.realTime.desc': 'Thông tin chi tiết toàn diện về tương tác khách hàng',
    'features.core.realTime.detail1': 'Giám sát hội thoại trực tiếp',
    'features.core.realTime.detail2': 'Metrics hiệu suất và KPIs',
    'features.core.realTime.detail3': 'Điểm hài lòng khách hàng',
    'features.core.realTime.detail4': 'Theo dõi ROI và chuyển đổi',

    'features.core.security.title': 'Bảo mật doanh nghiệp',
    'features.core.security.desc': 'Bảo mật cấp ngân hàng và tiêu chuẩn tuân thủ',
    'features.core.security.detail1': 'Mã hóa end-to-end',
    'features.core.security.detail2': 'Tuân thủ SOC 2 Type II',
    'features.core.security.detail3': 'Tuân thủ GDPR và bảo mật dữ liệu',
    'features.core.security.detail4': 'Tích hợp single sign-on (SSO)',

    'features.core.deployment.title': 'Triển khai tức thì',
    'features.core.deployment.desc': 'Khởi chạy trong vài phút với nền tảng no-code của chúng tôi',
    'features.core.deployment.detail1': 'Quy trình thiết lập 5 phút',
    'features.core.deployment.detail2': 'Mẫu và workflow có sẵn',
    'features.core.deployment.detail3': 'Trình tạo hội thoại drag-and-drop',
    'features.core.deployment.detail4': 'Tích hợp một cú nhấp chuột',

    'features.core.conversations.title': 'Cuộc trò chuyện thông minh',
    'features.core.conversations.desc': 'Tương tác giống con người chuyển đổi và thu hút',
    'features.core.conversations.detail1': 'Cá nhân hóa động',
    'features.core.conversations.detail2': 'Tự động hóa qualification khách hàng tiềm năng',
    'features.core.conversations.detail3': 'Đặt lịch hẹn và scheduling',
    'features.core.conversations.detail4': 'Gợi ý sản phẩm',

    // Comparison Table
    'features.comparison.title': 'AI Chatbots vs',
    'features.comparison.titleHighlight': 'Live Chat truyền thống',
    'features.comparison.subtitle': 'Xem cách tự động hóa AI vượt trội hơn các phương pháp dịch vụ khách hàng truyền thống',

    'features.comparison.tableHeader.feature': 'Tính năng',
    'features.comparison.tableHeader.traditional': 'Live Chat truyền thống',
    'features.comparison.tableHeader.aiChatbot': 'AI Chatbot',
    'features.comparison.tableHeader.improvement': 'Cải thiện',

    'features.comparison.responseTime': 'Thời gian phản hồi',
    'features.comparison.traditional.responseTime': 'Hàng giờ đến hàng ngày',
    'features.comparison.ai.responseTime': '< 2 giây',
    'features.comparison.improvement.responseTime': 'Nhanh hơn 99%',

    'features.comparison.availability': 'Khả năng sẵn sàng',
    'features.comparison.traditional.availability': 'Chỉ trong giờ làm việc',
    'features.comparison.ai.availability': '24/7/365',
    'features.comparison.improvement.availability': 'Luôn hoạt động',

    'features.comparison.scalability': 'Khả năng mở rộng',
    'features.comparison.traditional.scalability': 'Bị giới hạn bởi nhân viên',
    'features.comparison.ai.scalability': 'Hội thoại không giới hạn',
    'features.comparison.improvement.scalability': 'Quy mô vô hạn',

    'features.comparison.consistency': 'Tính nhất quán',
    'features.comparison.traditional.consistency': 'Khác nhau theo agent',
    'features.comparison.ai.consistency': 'Luôn nhất quán',
    'features.comparison.improvement.consistency': '100% đáng tin cậy',

    'features.comparison.costPerInteraction': 'Chi phí mỗi tương tác',
    'features.comparison.traditional.costPerInteraction': '120.000-360.000 VND',
    'features.comparison.ai.costPerInteraction': '2.500-12.000 VND',
    'features.comparison.improvement.costPerInteraction': 'Giảm chi phí 95%',

    'features.comparison.languageSupport': 'Hỗ trợ ngôn ngữ',
    'features.comparison.traditional.languageSupport': '1-2 ngôn ngữ',
    'features.comparison.ai.languageSupport': '50+ ngôn ngữ',
    'features.comparison.improvement.languageSupport': 'Phạm vi toàn cầu',

    // Advanced Features
    'features.advanced.title': 'Khả năng',
    'features.advanced.titleHighlight': 'nâng cao',
    'features.advanced.subtitle': 'Khám phá chức năng sâu sắc làm nên sự khác biệt của D2 Group',

    'features.advanced.ai.category': 'AI & Học máy',
    'features.advanced.ai.conversationFlow.name': 'Trình tạo luồng hội thoại',
    'features.advanced.ai.conversationFlow.desc': 'Giao diện kéo thả trực quan để thiết kế đường dẫn hội thoại phức tạp',
    'features.advanced.ai.intentTraining.name': 'Đào tạo ý định',
    'features.advanced.ai.intentTraining.desc': 'Liên tục cải thiện hiểu biết AI với dữ liệu đào tạo tùy chỉnh',
    'features.advanced.ai.autoLearning.name': 'Tự học',
    'features.advanced.ai.autoLearning.desc': 'Thuật toán học máy cải thiện phản hồi theo thời gian',
    'features.advanced.ai.fallbackHandling.name': 'Xử lý dự phòng',
    'features.advanced.ai.fallbackHandling.desc': 'Chuyển giao thông minh cho agent con người khi cần thiết',

    'features.advanced.integration.category': 'Tích hợp & APIs',
    'features.advanced.integration.crm.name': 'Tích hợp CRM',
    'features.advanced.integration.crm.desc': 'Kết nối với Salesforce, HubSpot, Pipedrive và 50+ CRM',
    'features.advanced.integration.ecommerce.name': 'Nền tảng thương mại điện tử',
    'features.advanced.integration.ecommerce.desc': 'Tích hợp native với Shopify, WooCommerce, Magento',
    'features.advanced.integration.customApi.name': 'APIs tùy chỉnh',
    'features.advanced.integration.customApi.desc': 'RESTful APIs cho tích hợp và workflow tùy chỉnh',
    'features.advanced.integration.webhook.name': 'Hỗ trợ Webhook',
    'features.advanced.integration.webhook.desc': 'Đồng bộ dữ liệu thời gian thực với hệ thống bên ngoài',

    'features.advanced.analytics.category': 'Phân tích & Báo cáo',
    'features.advanced.analytics.conversation.name': 'Phân tích hội thoại',
    'features.advanced.analytics.conversation.desc': 'Thông tin sâu sắc về hành vi khách hàng và mẫu hội thoại',
    'features.advanced.analytics.performance.name': 'Metrics hiệu suất',
    'features.advanced.analytics.performance.desc': 'Theo dõi tỷ lệ giải quyết, điểm hài lòng và metrics chuyển đổi',
    'features.advanced.analytics.dashboard.name': 'Dashboard tùy chỉnh',
    'features.advanced.analytics.dashboard.desc': 'Xây dựng dashboard báo cáo cá nhân hóa cho stakeholder',
    'features.advanced.analytics.abTesting.name': 'A/B Testing',
    'features.advanced.analytics.abTesting.desc': 'Kiểm tra các luồng hội thoại khác nhau và tối ưu hiệu suất',

    // Demo Section
    'features.demo.title': 'Xem tính năng của chúng tôi',
    'features.demo.titleHighlight': 'hoạt động',
    'features.demo.description': 'Trải nghiệm sức mạnh của nền tảng chatbot AI D2 Group với demo cá nhân hóa phù hợp với nhu cầu kinh doanh của bạn.',
    'features.demo.interactive.title': 'Demo tương tác',
    'features.demo.interactive.description': 'Nhấp để trải nghiệm chatbot của chúng tôi hoạt động',
    'features.demo.feature1': 'Luồng hội thoại thời gian thực',
    'features.demo.feature2': 'Hỗ trợ đa ngôn ngữ',
    'features.demo.feature3': 'Dashboard phân tích',
    'features.demo.bookDemo': 'Đặt lịch Demo trực tiếp',
    'features.demo.viewCaseStudies': 'Xem nghiên cứu trường hợp',
    
    // About Page
    'about.hero.title': 'Về D2 Group',
    'about.hero.subtitle': 'Chúng tôi đang thực hiện sứ mệnh chuyển đổi cách thức doanh nghiệp giao tiếp với khách hàng thông qua tự động hóa thông minh.',
    'about.hero.description': 'Từ năm 2019, chúng tôi đã tiên phong trong việc phát triển giải pháp chatbot AI mang lại kết quả thực tế.',
    'about.stats.clients': 'Khách hàng hài lòng',
    'about.stats.countries': 'Quốc gia phục vụ',
    'about.stats.uptime': 'Thời gian hoạt động SLA',
    'about.mission.title': 'Sứ mệnh của chúng tôi',
    'about.mission.description': 'Dân chủ hóa công nghệ AI và làm cho giao tiếp khách hàng thông minh trở nên dễ tiếp cận với các doanh nghiệp thuộc mọi quy mô. Chúng tôi tin rằng mọi công ty đều xứng đáng có khả năng tự động hóa cấp doanh nghiệp mà không cần phức tạp.',
    'about.mission.global.title': 'Phạm vi toàn cầu',
    'about.mission.global.desc': 'Phục vụ khách hàng trên khắp châu Á-Thái Bình Dương với các giải pháp được bản địa hóa',
    'about.mission.innovation.title': 'Đổi mới đi đầu',
    'about.mission.innovation.desc': 'Liên tục vượt qua ranh giới của AI đối thoại',
    'about.mission.security.title': 'Tin cậy & Bảo mật',
    'about.mission.security.desc': 'Tiêu chuẩn bảo mật và tuân thủ cấp doanh nghiệp',
    'about.vision.title': 'Tầm nhìn của chúng tôi',
    'about.vision.description': '"Một thế giới nơi mọi cuộc trò chuyện kinh doanh đều thông minh, được cá nhân hóa và thú vị - được hỗ trợ bởi AI thực sự hiểu nhu cầu con người."',
    'about.team.title': 'Gặp gỡ Đội ngũ của chúng tôi',
    'about.team.subtitle': 'Một nhóm đa dạng gồm các chuyên gia AI, kỹ sư và chiến lược gia kinh doanh được kết nối bởi niềm đam mê đổi mới',
    'about.journey.title': 'Hành trình của chúng tôi',
    'about.journey.subtitle': 'Từ startup đến nhà lãnh đạo ngành - những cột mốc định hình chúng tôi',
    'about.awards.title': 'Công nhận & Giải thưởng',
    'about.awards.subtitle': 'Sự công nhận của ngành về sự đổi mới và xuất sắc của chúng tôi',
    'about.cta.title': 'Sẵn sàng tham gia Câu chuyện thành công của chúng tôi?',
    'about.cta.description': 'Hãy thảo luận về cách D2 Group có thể chuyển đổi chiến lược giao tiếp khách hàng của bạn. Đội ngũ của chúng tôi sẵn sàng thiết kế giải pháp phù hợp với nhu cầu riêng của bạn.',
    'about.cta.getStarted': 'Bắt đầu ngay hôm nay',
    'about.cta.scheduleCall': 'Đặt lịch gọi',
    
    // Case Studies Page
    'caseStudies.hero.title': 'Nghiên cứu trường hợp',
    'caseStudies.hero.subtitle': 'Kết quả thực tế từ các doanh nghiệp đã chuyển đổi thành công',
    'caseStudies.hero.description': 'Khám phá cách các công ty như bạn đã đạt được kết quả đáng kể với giải pháp chatbot AI của chúng tôi.',
    'caseStudies.filter.all': 'Tất cả ngành',
    'caseStudies.filter.ecommerce': 'Thương mại điện tử',
    'caseStudies.filter.healthcare': 'Chăm sóc sức khỏe',
    'caseStudies.filter.education': 'Giáo dục',
    'caseStudies.filter.banking': 'Ngân hàng',
    'caseStudies.filter.realestate': 'Bất động sản',
    'caseStudies.filter.travel': 'Du lịch',
    
    'caseStudies.metrics.conversion': 'Tăng chuyển đổi',
    'caseStudies.metrics.satisfaction': 'Hài lòng khách hàng',
    'caseStudies.metrics.reduction': 'Giảm chi phí hỗ trợ',
    'caseStudies.metrics.response': 'Thời gian phản hồi',
    'caseStudies.metrics.automation': 'Tự động hóa',
    'caseStudies.readMore': 'Đọc thêm',
    'caseStudies.viewDetails': 'Xem chi tiết',
    'caseStudies.downloadPdf': 'Tải PDF',
    
    'caseStudies.ecommerce.title': 'Cửa hàng thời trang trực tuyến tăng 150% doanh số',
    'caseStudies.ecommerce.company': 'FashionHub Vietnam',
    'caseStudies.ecommerce.challenge': 'Tỷ lệ bỏ giỏ hàng cao và hỗ trợ khách hàng chậm trễ',
    'caseStudies.ecommerce.solution': 'Triển khai chatbot AI để tư vấn sản phẩm và hỗ trợ thanh toán',
    'caseStudies.ecommerce.result': 'Giảm 60% tỷ lệ bỏ giỏ hàng và tăng 150% doanh số trong 6 tháng',
    
    'caseStudies.healthcare.title': 'Bệnh viện cải thiện 90% hài lòng bệnh nhân',
    'caseStudies.healthcare.company': 'Bệnh viện Đa khoa Sài Gòn',
    'caseStudies.healthcare.challenge': 'Quá tải hotline và thời gian chờ đợi lâu',
    'caseStudies.healthcare.solution': 'Chatbot hỗ trợ đặt lịch khám và tư vấn sức khỏe cơ bản',
    'caseStudies.healthcare.result': 'Giảm 70% cuộc gọi hotline và tăng 90% điểm hài lòng bệnh nhân',
    
    'caseStudies.education.title': 'Trường đại học tăng 200% tương tác sinh viên',
    'caseStudies.education.company': 'Đại học Công nghệ TP.HCM',
    'caseStudies.education.challenge': 'Sinh viên khó tiếp cận thông tin và dịch vụ hỗ trợ',
    'caseStudies.education.solution': 'Chatbot hỗ trợ tư vấn học tập và thủ tục hành chính',
    'caseStudies.education.result': 'Tăng 200% tương tác và giảm 80% thời gian xử lý thủ tục',
    
    'caseStudies.cta.title': 'Sẵn sàng đạt được kết quả tương tự?',
    'caseStudies.cta.description': 'Hãy để chúng tôi giúp bạn tạo ra câu chuyện thành công của riêng mình.',
    'caseStudies.cta.getStarted': 'Bắt đầu ngay',
    'caseStudies.cta.contactUs': 'Liên hệ tư vấn',
    
    // Pricing Page
    'pricing.title': 'Bảng giá đơn giản và minh bạch',
    'pricing.subtitle': 'Chọn gói phù hợp với nhu cầu doanh nghiệp của bạn. Tất cả các gói đều bao gồm thiết lập miễn phí, đào tạo và dùng thử 14 ngày không cam kết.',
    'pricing.starter': 'Starter',
    'pricing.growth': 'Growth', 
    'pricing.business': 'Business',
    'pricing.enterprise': 'Enterprise',
    'pricing.month': '/tháng',
    'pricing.contactPricing': 'Liên hệ để báo giá',
    'pricing.getStarted': 'Bắt đầu',
    'pricing.contactForPricing': 'Liên hệ để báo giá',
    'pricing.freeTrial': 'Dùng thử 14 ngày miễn phí',
    'pricing.noSetupFees': 'Không phí thiết lập',
    'pricing.cancelAnytime': 'Hủy bất cứ lúc nào',
    'pricing.mostPopular': 'Phổ biến nhất',
    
    // Plan descriptions
    'pricing.starter.desc': 'Hoàn hảo cho các doanh nghiệp nhỏ mới bắt đầu với chatbot AI',
    'pricing.growth.desc': 'Lý tưởng cho các công ty đang phát triển với nhu cầu tương tác cao hơn',
    'pricing.business.desc': 'Giải pháp toàn diện cho các doanh nghiệp có yêu cầu chuyên nghiệp',
    'pricing.enterprise.desc': 'Giải pháp tùy chỉnh cho các tổ chức lớn với yêu cầu cụ thể',
    
    // Pricing Features
    'pricing.features.coreFeatures': 'Tính năng cốt lõi',
    'pricing.features.channelsIntegrations': 'Kênh & Tích hợp',
    'pricing.features.analyticsReporting': 'Phân tích & Báo cáo',
    'pricing.features.securityCompliance': 'Bảo mật & Tuân thủ',
    'pricing.features.supportServices': 'Hỗ trợ & Dịch vụ',
    
    'pricing.features.monthlyChatSessions': 'Phiên chat hàng tháng',
    'pricing.features.chatbotTemplate': 'Mẫu chatbot',
    'pricing.features.responseTimeSla': 'SLA thời gian phản hồi',
    'pricing.features.analyticsDashboard': 'Bảng điều khiển phân tích',
    'pricing.features.websiteWidget': 'Widget website',
    'pricing.features.whatsappBusiness': 'WhatsApp Business',
    'pricing.features.facebookMessenger': 'Facebook Messenger',
    'pricing.features.crmIntegration': 'Tích hợp CRM',
    'pricing.features.customApiAccess': 'Truy cập API tùy chỉnh',
    
    'pricing.comparison.title': 'So sánh chi tiết',
    'pricing.comparison.subtitle': 'So sánh tất cả tính năng giữa các gói cước của chúng tôi.',
    'pricing.comparison.features': 'Tính năng',
    
    'pricing.faq.title': 'Câu hỏi thường gặp',
    'pricing.faq.subtitle': 'Mọi thứ bạn cần biết về bảng giá và gói dịch vụ của chúng tôi.',
    'pricing.faq.q1': 'Phiên chat được tính như thế nào?',
    'pricing.faq.a1': 'Một phiên chat được tính mỗi khi người dùng duy nhất tương tác với chatbot trong khung thời gian 24 giờ, bất kể số lượng tin nhắn trao đổi.',
    'pricing.faq.q2': 'Tôi có thể nâng cấp hoặc hạ cấp gói bất cứ lúc nào không?',
    'pricing.faq.a2': 'Có - bạn có thể chuyển đổi gói bất cứ lúc nào. Nâng cấp có hiệu lực ngay lập tức; hạ cấp áp dụng trong chu kỳ thanh toán tiếp theo.',
    'pricing.faq.q3': 'Có dùng thử miễn phí không?',
    'pricing.faq.a3': 'Có - chúng tôi cung cấp dùng thử 14 ngày miễn phí cho tất cả các gói. Không cần thẻ tín dụng và bạn có thể hủy bất cứ lúc nào trong thời gian dùng thử.',
    'pricing.faq.q4': 'Điều gì xảy ra nếu tôi vượt quá giới hạn phiên chat?',
    'pricing.faq.a4': 'Nếu bạn vượt quá hạn ngạch hàng tháng, các phiên bổ sung sẽ được tính phí 3.000 VND mỗi phiên. Chúng tôi sẽ gửi thông báo khi bạn gần đạt giới hạn.',
    
    'pricing.cta.title': 'Sẵn sàng bắt đầu?',
    'pricing.cta.description': 'Tham gia cùng hàng trăm doanh nghiệp đã chuyển đổi trải nghiệm khách hàng với D2 Group. Bắt đầu dùng thử miễn phí ngay hôm nay.',
    'pricing.cta.startTrial': 'Bắt đầu dùng thử miễn phí',
    'pricing.cta.contactSales': 'Liên hệ bán hàng',
    
    // Contact Page
    'contact.hero.title': 'Liên hệ với chúng tôi',
    'contact.hero.subtitle': 'Sẵn sàng chuyển đổi trải nghiệm khách hàng của bạn?',
    'contact.hero.description': 'Hãy bắt đầu cuộc trò chuyện. Đội ngũ chuyên gia của chúng tôi sẵn sàng thảo luận về nhu cầu của bạn và thiết kế giải pháp phù hợp.',
    
    'contact.form.title': 'Gửi tin nhắn cho chúng tôi',
    'contact.form.subtitle': 'Điền thông tin bên dưới và chúng tôi sẽ liên hệ với bạn trong vòng 24 giờ',
    'contact.form.name': 'Họ và tên',
    'contact.form.name.placeholder': 'Nhập họ và tên của bạn',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'Nhập địa chỉ email của bạn',
    'contact.form.company': 'Công ty',
    'contact.form.company.placeholder': 'Nhập tên công ty của bạn',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.phone.placeholder': 'Nhập số điện thoại của bạn',
    'contact.form.subject': 'Chủ đề',
    'contact.form.subject.placeholder': 'Chọn chủ đề quan tâm',
    'contact.form.subject.demo': 'Đặt lịch Demo',
    'contact.form.subject.pricing': 'Tư vấn giá cả',
    'contact.form.subject.support': 'Hỗ trợ kỹ thuật',
    'contact.form.subject.partnership': 'Hợp tác kinh doanh',
    'contact.form.subject.other': 'Khác',
    'contact.form.message': 'Tin nhắn',
    'contact.form.message.placeholder': 'Chia sẻ chi tiết về nhu cầu hoặc dự án của bạn...',
    'contact.form.send': 'Gửi tin nhắn',
    'contact.form.sending': 'Đang gửi...',
    'contact.form.success': 'Tin nhắn đã được gửi thành công! Chúng tôi sẽ liên hệ với bạn sớm.',
    'contact.form.error': 'Có lỗi xảy ra. Vui lòng thử lại sau.',
    
    'contact.info.title': 'Thông tin liên hệ',
    'contact.info.subtitle': 'Nhiều cách để kết nối với chúng tôi',
    'contact.info.address': 'Địa chỉ',
    'contact.info.address.detail': 'Số 3 Nguyễn Cơ Thạch, Phường An Lợi Đông, Thành phố Thủ Đức, TP.HCM',
    'contact.info.phone': 'Điện thoại',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Giờ làm việc',
    'contact.info.hours.detail': 'Thứ 2 - Thứ 6: 8:00 - 18:00',
    'contact.info.weekend': 'Thứ 7 - Chủ nhật: 9:00 - 17:00',
    'contact.info.response': 'Thời gian phản hồi',
    'contact.info.response.detail': 'Trung bình dưới 2 giờ trong giờ làm việc',
    
    'contact.demo.title': 'Đặt lịch Demo',
    'contact.demo.subtitle': 'Xem D2 Group hoạt động trong demo cá nhân hóa',
    'contact.demo.description': 'Đặt lịch demo 30 phút để khám phá cách chatbot AI có thể chuyển đổi doanh nghiệp của bạn.',
    'contact.demo.book': 'Đặt lịch Demo',
    'contact.demo.features': 'Demo bao gồm:',
    'contact.demo.feature1': 'Tổng quan về nền tảng và tính năng',
    'contact.demo.feature2': 'Thiết lập chatbot mẫu cho ngành của bạn',
    'contact.demo.feature3': 'Q&A với chuyên gia giải pháp',
    'contact.demo.feature4': 'Tư vấn chiến lược và lộ trình triển khai',
    
    'contact.support.title': 'Hỗ trợ khách hàng',
    'contact.support.subtitle': 'Chúng tôi luôn sẵn sàng hỗ trợ bạn',
    'contact.support.technical': 'Hỗ trợ kỹ thuật',
    'contact.support.technical.desc': 'Giải đáp thắc mắc về tính năng và sử dụng',
    'contact.support.billing': 'Hỗ trợ thanh toán',
    'contact.support.billing.desc': 'Thắc mắc về hóa đơn và gói dịch vụ',
    'contact.support.training': 'Đào tạo và hướng dẫn',
    'contact.support.training.desc': 'Học cách sử dụng nền tảng hiệu quả',
    
    'contact.social.title': 'Kết nối với chúng tôi',
    'contact.social.subtitle': 'Theo dõi cập nhật mới nhất và chia sẻ kinh nghiệm',
    
    // Footer
    'footer.company': 'Công ty',
    'footer.product': 'Sản phẩm',
    'footer.resources': 'Tài nguyên',
    'footer.support': 'Hỗ trợ',
    'footer.legal': 'Pháp lý',
    'footer.blog': 'Blog',
    'footer.documentation': 'Tài liệu',
    'footer.apiDocs': 'Tài liệu API',
    'footer.helpCenter': 'Trung tâm trợ giúp',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.terms': 'Điều khoản dịch vụ',
    'footer.security': 'Bảo mật',
    'footer.status': 'Trạng thái hệ thống',
    'footer.followUs': 'Theo dõi chúng tôi',
    'footer.newsletter.title': 'Đăng ký nhận tin',
    'footer.newsletter.description': 'Nhận cập nhật mới nhất về sản phẩm và tin tức ngành',
    'footer.newsletter.placeholder': 'Nhập email của bạn',
    'footer.newsletter.subscribe': 'Đăng ký',
    'footer.copyright': '© 2024 D2 Group. Tất cả quyền được bảo lưu.',
    
    // 404 Page
    'notFound.title': 'Không tìm thấy trang',
    'notFound.description': 'Xin lỗi, trang bạn đang tìm kiếm không tồn tại hoặc đã bị di chuyển.',
    'notFound.backHome': 'Về trang chủ',
    'notFound.contactSupport': 'Liên hệ hỗ trợ',
    'notFound.errorCode': 'Mã lỗi:',
    
    // Form Validation
    'validation.required': 'Trường này là bắt buộc',
    'validation.email': 'Vui lòng nhập email hợp lệ',
    'validation.phone': 'Vui lòng nhập số điện thoại hợp lệ',
    'validation.minLength': 'Tối thiểu {min} ký tự',
    'validation.maxLength': 'Tối đa {max} ký tự',
    
    // System Messages
    'system.loading': 'Đang tải...',
    'system.error': 'Đã xảy ra lỗi',
    'system.success': 'Thành công!',
    'system.tryAgain': 'Thử lại',
    'system.cancel': 'Hủy',
    'system.confirm': 'Xác nhận',
    'system.save': 'Lưu',
    'system.edit': 'Chỉnh sửa',
    'system.delete': 'Xóa',
    'system.view': 'Xem',
    'system.download': 'Tải xuống',
    'system.upload': 'Tải lên',
    'system.search': 'Tìm kiếm',
    'system.filter': 'Lọc',
    'system.sort': 'Sắp xếp',
    'system.next': 'Tiếp theo',
    'system.previous': 'Trước',
    'system.close': 'Đóng',
    'system.open': 'Mở',
    'system.expand': 'Mở rộng',
    'system.collapse': 'Thu gọn',
    
    // Common terms
    'common.worksWith': 'Hoạt động với',
    'common.includes': 'Bao gồm',
    'common.plus': 'Cộng',
    'common.per': 'mỗi',
    'common.up': 'Lên đến',
    'common.from': 'Từ',
    'common.to': 'Đến',
    'common.and': 'và',
    'common.or': 'hoặc',
    'common.all': 'Tất cả',
    'common.more': 'Thêm',
    'common.less': 'Ít hơn',
    'common.new': 'Mới',
    'common.popular': 'Phổ biến',
    'common.recommended': 'Đề xuất',
    'common.featured': 'Nổi bật',
    'common.free': 'Miễn phí',
    'common.premium': 'Cao cấp',
    'common.pro': 'Chuyên nghiệp',
    'common.basic': 'Cơ bản',
    'common.advanced': 'Nâng cao',
    'common.custom': 'Tùy chỉnh',
    'common.standard': 'Tiêu chuẩn',
    'common.enterprise': 'Doanh nghiệp',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.features': 'Features', 
    'nav.caseStudies': 'Case Studies',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.getDemo': 'Get Demo',
    'nav.contactUs': 'Contact Us',
    
    // Home Page
    'home.hero.title': 'Supercharge',
    'home.hero.subtitle': 'Customer Conversations',
    'home.hero.subtitle2': 'with',
    'home.hero.subtitle3': 'AI-Driven Chatbots',
    'home.hero.description': 'Transform customer support into a revenue driver.\nDeploy intelligent chatbots that engage, convert, and delight customers 24/7.',
    'home.hero.getDemo': 'Get Free Demo',
    'home.hero.learnMore': 'Learn More',
    
    // Why D2 Group
    'home.why.title': 'Why Choose',
    'home.why.subtitle': 'We combine cutting-edge AI technology with deep business expertise to deliver chatbots that truly understand your customers',
    'home.why.ai.title': 'AI-Powered Intelligence',
    'home.why.ai.desc': 'Advanced natural language processing that understands context and intent',
    'home.why.security.title': 'Enterprise Security',
    'home.why.security.desc': 'Bank-grade encryption and compliance with global security standards',
    'home.why.results.title': 'Proven Results',
    'home.why.results.desc': 'Average 40% increase in conversions and 60% reduction in support costs',
    'home.why.learnMore': 'Learn More About Us',
    
    // Key Features
    'home.features.title': 'Key Features',
    'home.features.subtitle': 'Everything you need to automate and enhance customer conversations',
    'home.features.smart.title': 'Smart Conversations',
    'home.features.smart.desc': 'Natural dialogue that feels human',
    'home.features.instant.title': 'Instant Setup',
    'home.features.instant.desc': 'Deploy in under 5 minutes',
    'home.features.analytics.title': 'Real-time Analytics',
    'home.features.analytics.desc': 'Track performance and optimize',
    'home.features.multichannel.title': 'Multi-channel',
    'home.features.multichannel.desc': 'Website, WhatsApp, Facebook',
    'home.features.viewAll': 'View All Features',
    
    // How It Works
    'home.howItWorks.title': 'How It Works',
    'home.howItWorks.subtitle': 'Get up and running in 3 simple steps',
    'home.howItWorks.step1.title': 'Connect Your Data',
    'home.howItWorks.step1.desc': 'Upload your FAQs, product info, and knowledge base',
    'home.howItWorks.step2.title': 'Train Your Bot',
    'home.howItWorks.step2.desc': 'AI learns your business and customer patterns',
    'home.howItWorks.step3.title': 'Deploy & Scale',
    'home.howItWorks.step3.desc': 'Launch across channels and watch conversions grow',
    
    // Use Cases
    'home.useCases.title': 'Proven Results',
    'home.useCases.subtitle': 'See how businesses like yours are winning with AI chatbots',
    'home.useCases.ecommerce': 'E-commerce',
    'home.useCases.healthcare': 'Healthcare',
    'home.useCases.education': 'Education',
    'home.useCases.banking': 'Banking',
    'home.useCases.realestate': 'Real Estate',
    'home.useCases.travel': 'Travel',
    'home.useCases.viewCaseStudies': 'View Case Studies',
    
    // Testimonials
    'home.testimonials.title': 'What Our Customers Say',
    'home.testimonials.subtitle': 'Join 500+ businesses already transforming their customer experience',
    'home.testimonials.1.content': 'D2 Group\'s chatbot increased our lead conversion by 45% in just 3 months. The AI truly understands our customers.',
    'home.testimonials.2.content': 'The 24/7 customer support automation has revolutionized our service quality. Customers love the instant responses.',
    'home.testimonials.3.content': 'Implementation was seamless and ROI was visible within weeks. Our student satisfaction scores hit an all-time high.',
    
    // Partners
    'home.partners.title': 'Trusted by Leading Organizations',
    'home.partners.subtitle': 'Join these industry leaders who have deployed our solutions',
    
    // Home Pricing
    'home.pricing.title': 'Simple, Transparent Pricing',
    'home.pricing.subtitle': 'Choose the plan that fits your business needs',
    'home.pricing.seeFullPricing': 'See Full Pricing',
    
    // FAQ
    'home.faq.title': 'Frequently Asked Questions',
    'home.faq.subtitle': 'Quick answers to common questions',
    'home.faq.q1': 'How quickly can we deploy the chatbot?',
    'home.faq.a1': 'Most clients are live within 24-48 hours. Basic setup takes just 5 minutes.',
    'home.faq.q2': 'Does it integrate with our existing CRM?',
    'home.faq.a2': 'Yes, we integrate with 50+ platforms including Salesforce, HubSpot, and custom APIs.',
    'home.faq.q3': 'What\'s the expected ROI?',
    'home.faq.a3': 'Clients typically see 3-5x ROI within 6 months through increased conversions and reduced support costs.',
    'home.faq.viewFullFaq': 'View Full FAQ',
    
    // Final CTA
    'home.finalCta.title': 'Ready to',
    'home.finalCta.title2': 'Automate',
    'home.finalCta.title3': 'Your Customer Conversations?',
    'home.finalCta.description': 'Join hundreds of businesses that have already transformed their customer experience with D2 Group\'s AI chatbots. Start your free trial today and see results within 48 hours.',
    'home.finalCta.startTrial': 'Start Free Trial',
    'home.finalCta.bookDemo': 'Book a Demo',
    'home.finalCta.freeTrial': 'Free 14-day trial',
    'home.finalCta.noCreditCard': 'No credit card required',
    'home.finalCta.setupIn5': 'Setup in 5 minutes',

    // Features Page
    'features.hero.title': 'Powerful',
    'features.hero.titleHighlight': 'Features',
    'features.hero.titleEnd': 'That Drive Results',
    'features.hero.description': 'Discover the comprehensive suite of AI-powered features designed to transform your customer communication and drive measurable business growth.',
    'features.hero.cta': 'See Features in Action',

    // Core Features
    'features.core.title': 'Core',
    'features.core.titleHighlight': 'Capabilities',
    'features.core.subtitle': 'Everything you need to deliver exceptional customer experiences',

    'features.core.nlp.title': 'Natural Language Processing',
    'features.core.nlp.desc': 'Advanced AI that understands context, intent, and sentiment',
    'features.core.nlp.detail1': 'Multi-language support with 95%+ accuracy',
    'features.core.nlp.detail2': 'Contextual conversation flow management',
    'features.core.nlp.detail3': 'Sentiment analysis and emotion detection',
    'features.core.nlp.detail4': 'Intent recognition and entity extraction',

    'features.core.multiChannel.title': 'Omnichannel Deployment',
    'features.core.multiChannel.desc': 'Deploy across website, WhatsApp, Facebook, and more',
    'features.core.multiChannel.detail1': 'Website chat widget with customizable UI',
    'features.core.multiChannel.detail2': 'WhatsApp Business API integration',
    'features.core.multiChannel.detail3': 'Facebook Messenger connectivity',
    'features.core.multiChannel.detail4': 'SMS and voice channel support',

    'features.core.realTime.title': 'Real-time Analytics',
    'features.core.realTime.desc': 'Comprehensive insights into customer interactions',
    'features.core.realTime.detail1': 'Live conversation monitoring',
    'features.core.realTime.detail2': 'Performance metrics and KPIs',
    'features.core.realTime.detail3': 'Customer satisfaction scoring',
    'features.core.realTime.detail4': 'ROI and conversion tracking',

    'features.core.security.title': 'Enterprise Security',
    'features.core.security.desc': 'Bank-grade security and compliance standards',
    'features.core.security.detail1': 'End-to-end encryption',
    'features.core.security.detail2': 'SOC 2 Type II compliant',
    'features.core.security.detail3': 'GDPR and data privacy compliance',
    'features.core.security.detail4': 'Single sign-on (SSO) integration',

    'features.core.deployment.title': 'Instant Deployment',
    'features.core.deployment.desc': 'Go live in minutes with our no-code platform',
    'features.core.deployment.detail1': '5-minute setup process',
    'features.core.deployment.detail2': 'Pre-built templates and workflows',
    'features.core.deployment.detail3': 'Drag-and-drop conversation builder',
    'features.core.deployment.detail4': 'One-click integrations',

    'features.core.conversations.title': 'Smart Conversations',
    'features.core.conversations.desc': 'Human-like interactions that convert and engage',
    'features.core.conversations.detail1': 'Dynamic personalization',
    'features.core.conversations.detail2': 'Lead qualification automation',
    'features.core.conversations.detail3': 'Appointment booking and scheduling',
    'features.core.conversations.detail4': 'Product recommendations',

    // Comparison Table
    'features.comparison.title': 'AI Chatbots vs',
    'features.comparison.titleHighlight': 'Traditional Live Chat',
    'features.comparison.subtitle': 'See how AI-powered automation outperforms traditional customer service methods',

    'features.comparison.tableHeader.feature': 'Feature',
    'features.comparison.tableHeader.traditional': 'Traditional Live Chat',
    'features.comparison.tableHeader.aiChatbot': 'AI Chatbot',
    'features.comparison.tableHeader.improvement': 'Improvement',

    'features.comparison.responseTime': 'Response Time',
    'features.comparison.traditional.responseTime': 'Hours to days',
    'features.comparison.ai.responseTime': '< 2 seconds',
    'features.comparison.improvement.responseTime': '99% faster',

    'features.comparison.availability': 'Availability',
    'features.comparison.traditional.availability': 'Business hours only',
    'features.comparison.ai.availability': '24/7/365',
    'features.comparison.improvement.availability': 'Always on',

    'features.comparison.scalability': 'Scalability',
    'features.comparison.traditional.scalability': 'Limited by staff',
    'features.comparison.ai.scalability': 'Unlimited conversations',
    'features.comparison.improvement.scalability': 'Infinite scale',

    'features.comparison.consistency': 'Consistency',
    'features.comparison.traditional.consistency': 'Varies by agent',
    'features.comparison.ai.consistency': 'Always consistent',
    'features.comparison.improvement.consistency': '100% reliable',

    'features.comparison.costPerInteraction': 'Cost per Interaction',
    'features.comparison.traditional.costPerInteraction': '$5-15',
    'features.comparison.ai.costPerInteraction': '$0.10-0.50',
    'features.comparison.improvement.costPerInteraction': '95% cost reduction',

    'features.comparison.languageSupport': 'Language Support',
    'features.comparison.traditional.languageSupport': '1-2 languages',
    'features.comparison.ai.languageSupport': '50+ languages',
    'features.comparison.improvement.languageSupport': 'Global reach',

    // Advanced Features
    'features.advanced.title': 'Advanced',
    'features.advanced.titleHighlight': 'Capabilities',
    'features.advanced.subtitle': 'Explore the deep functionality that sets D2 Group apart',

    'features.advanced.ai.category': 'AI & Machine Learning',
    'features.advanced.ai.conversationFlow.name': 'Conversation Flow Builder',
    'features.advanced.ai.conversationFlow.desc': 'Visual drag-and-drop interface to design complex conversation paths',
    'features.advanced.ai.intentTraining.name': 'Intent Training',
    'features.advanced.ai.intentTraining.desc': 'Continuously improve AI understanding with custom training data',
    'features.advanced.ai.autoLearning.name': 'Auto-Learning',
    'features.advanced.ai.autoLearning.desc': 'Machine learning algorithms that improve responses over time',
    'features.advanced.ai.fallbackHandling.name': 'Fallback Handling',
    'features.advanced.ai.fallbackHandling.desc': 'Smart escalation to human agents when needed',

    'features.advanced.integration.category': 'Integration & APIs',
    'features.advanced.integration.crm.name': 'CRM Integration',
    'features.advanced.integration.crm.desc': 'Connect with Salesforce, HubSpot, Pipedrive, and 50+ CRMs',
    'features.advanced.integration.ecommerce.name': 'E-commerce Platforms',
    'features.advanced.integration.ecommerce.desc': 'Native integration with Shopify, WooCommerce, Magento',
    'features.advanced.integration.customApi.name': 'Custom APIs',
    'features.advanced.integration.customApi.desc': 'RESTful APIs for custom integrations and workflows',
    'features.advanced.integration.webhook.name': 'Webhook Support',
    'features.advanced.integration.webhook.desc': 'Real-time data synchronization with external systems',

    'features.advanced.analytics.category': 'Analytics & Reporting',
    'features.advanced.analytics.conversation.name': 'Conversation Analytics',
    'features.advanced.analytics.conversation.desc': 'Deep insights into customer behavior and conversation patterns',
    'features.advanced.analytics.performance.name': 'Performance Metrics',
    'features.advanced.analytics.performance.desc': 'Track resolution rate, satisfaction scores, and conversion metrics',
    'features.advanced.analytics.dashboard.name': 'Custom Dashboards',
    'features.advanced.analytics.dashboard.desc': 'Build personalized reporting dashboards for stakeholders',
    'features.advanced.analytics.abTesting.name': 'A/B Testing',
    'features.advanced.analytics.abTesting.desc': 'Test different conversation flows and optimize performance',

    // Demo Section
    'features.demo.title': 'See Our Features',
    'features.demo.titleHighlight': 'In Action',
    'features.demo.description': 'Experience the power of D2 Group\'s AI chatbot platform with a personalized demo tailored to your business needs.',
    'features.demo.interactive.title': 'Interactive Demo',
    'features.demo.interactive.description': 'Click to experience our chatbot in action',
    'features.demo.feature1': 'Real-time conversation flow',
    'features.demo.feature2': 'Multi-language support',
    'features.demo.feature3': 'Analytics dashboard',
    'features.demo.bookDemo': 'Book Live Demo',
    'features.demo.viewCaseStudies': 'View Case Studies',
    
    // About Page
    'about.hero.title': 'About D2 Group',
    'about.hero.subtitle': 'We\'re on a mission to transform how businesses communicate with their customers through intelligent automation.',
    'about.hero.description': 'Since 2019, we\'ve been pioneering AI-driven chatbot solutions that deliver real results.',
    'about.stats.clients': 'Happy Clients',
    'about.stats.countries': 'Countries Served',
    'about.stats.uptime': 'Uptime SLA',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To democratize AI technology and make intelligent customer communication accessible to businesses of all sizes. We believe every company deserves enterprise-grade automation capabilities without the complexity.',
    'about.mission.global.title': 'Global Reach',
    'about.mission.global.desc': 'Serving clients across Asia-Pacific with localized solutions',
    'about.mission.innovation.title': 'Innovation First',
    'about.mission.innovation.desc': 'Constantly pushing the boundaries of conversational AI',
    'about.mission.security.title': 'Trust & Security',
    'about.mission.security.desc': 'Enterprise-grade security and compliance standards',
    'about.vision.title': 'Our Vision',
    'about.vision.description': '"A world where every business conversation is intelligent, personalized, and delightful - powered by AI that truly understands human needs."',
    'about.team.title': 'Meet Our Team',
    'about.team.subtitle': 'A diverse group of AI experts, engineers, and business strategists united by our passion for innovation',
    'about.journey.title': 'Our Journey',
    'about.journey.subtitle': 'From startup to industry leader - the milestones that define us',
    'about.awards.title': 'Recognition & Awards',
    'about.awards.subtitle': 'Industry recognition for our innovation and excellence',
    'about.cta.title': 'Ready to Join Our Success Story?',
    'about.cta.description': 'Let\'s discuss how D2 Group can transform your customer communication strategy. Our team is ready to design a solution that fits your unique needs.',
    'about.cta.getStarted': 'Get Started Today',
    'about.cta.scheduleCall': 'Schedule a Call',
    
    // Case Studies Page
    'caseStudies.hero.title': 'Case Studies',
    'caseStudies.hero.subtitle': 'Real results from businesses that have successfully transformed',
    'caseStudies.hero.description': 'Discover how companies like yours have achieved remarkable results with our AI chatbot solutions.',
    'caseStudies.filter.all': 'All Industries',
    'caseStudies.filter.ecommerce': 'E-commerce',
    'caseStudies.filter.healthcare': 'Healthcare',
    'caseStudies.filter.education': 'Education',
    'caseStudies.filter.banking': 'Banking',
    'caseStudies.filter.realestate': 'Real Estate',
    'caseStudies.filter.travel': 'Travel',
    
    'caseStudies.metrics.conversion': 'Increase in conversions',
    'caseStudies.metrics.satisfaction': 'Customer satisfaction',
    'caseStudies.metrics.reduction': 'Support cost reduction',
    'caseStudies.metrics.response': 'Response time',
    'caseStudies.metrics.automation': 'Automation',
    'caseStudies.readMore': 'Read More',
    'caseStudies.viewDetails': 'View Details',
    'caseStudies.downloadPdf': 'Download PDF',
    
    'caseStudies.ecommerce.title': 'Fashion retailer increases sales by 150%',
    'caseStudies.ecommerce.company': 'FashionHub Vietnam',
    'caseStudies.ecommerce.challenge': 'High cart abandonment rates and slow customer support',
    'caseStudies.ecommerce.solution': 'Deployed AI chatbot for product advice and checkout assistance',
    'caseStudies.ecommerce.result': '60% reduction in cart abandonment and 150% increase in sales within 6 months',
    
    'caseStudies.healthcare.title': 'Hospital improves patient satisfaction by 90%',
    'caseStudies.healthcare.company': 'Saigon General Hospital',
    'caseStudies.healthcare.challenge': 'Overloaded hotlines and long waiting times',
    'caseStudies.healthcare.solution': 'Chatbot supporting appointment booking and basic health consultation',
    'caseStudies.healthcare.result': '70% reduction in hotline calls and 90% increase in patient satisfaction scores',
    
    'caseStudies.education.title': 'University increases student engagement by 200%',
    'caseStudies.education.company': 'Ho Chi Minh City University of Technology',
    'caseStudies.education.challenge': 'Students struggling to access information and support services',
    'caseStudies.education.solution': 'Chatbot supporting academic advice and administrative procedures',
    'caseStudies.education.result': '200% increase in engagement and 80% reduction in procedure processing time',
    
    'caseStudies.cta.title': 'Ready to achieve similar results?',
    'caseStudies.cta.description': 'Let us help you create your own success story.',
    'caseStudies.cta.getStarted': 'Get Started',
    'caseStudies.cta.contactUs': 'Contact for Consultation',
    
    // Pricing Page
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your business needs. All plans include free setup, training, and a 14-day free trial with no commitments.',
    'pricing.starter': 'Starter',
    'pricing.growth': 'Growth',
    'pricing.business': 'Business', 
    'pricing.enterprise': 'Enterprise',
    'pricing.month': '/month',
    'pricing.contactPricing': 'Contact for pricing',
    'pricing.getStarted': 'Get Started',
    'pricing.contactForPricing': 'Contact for Pricing',
    'pricing.freeTrial': 'Free 14-day trial',
    'pricing.noSetupFees': 'No setup fees',
    'pricing.cancelAnytime': 'Cancel anytime',
    'pricing.mostPopular': 'Most Popular',
    
    // Plan descriptions
    'pricing.starter.desc': 'Perfect for small businesses getting started with AI chatbots',
    'pricing.growth.desc': 'Ideal for growing companies with higher volume needs',
    'pricing.business.desc': 'Comprehensive solution for businesses with professional requirements',
    'pricing.enterprise.desc': 'Tailored solutions for large organizations with specific requirements',
    
    // Pricing Features
    'pricing.features.coreFeatures': 'Core Features',
    'pricing.features.channelsIntegrations': 'Channels & Integrations',
    'pricing.features.analyticsReporting': 'Analytics & Reporting',
    'pricing.features.securityCompliance': 'Security & Compliance',
    'pricing.features.supportServices': 'Support & Services',
    
    'pricing.features.monthlyChatSessions': 'Monthly chat sessions',
    'pricing.features.chatbotTemplate': 'Chatbot templates',
    'pricing.features.responseTimeSla': 'Response time SLA',
    'pricing.features.analyticsDashboard': 'Analytics dashboard',
    'pricing.features.websiteWidget': 'Website widget',
    'pricing.features.whatsappBusiness': 'WhatsApp Business',
    'pricing.features.facebookMessenger': 'Facebook Messenger',
    'pricing.features.crmIntegration': 'CRM integrations',
    'pricing.features.customApiAccess': 'Custom API access',
    
    'pricing.comparison.title': 'Detailed Comparison',
    'pricing.comparison.subtitle': 'Compare all features across our pricing plans.',
    'pricing.comparison.features': 'Features',
    
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.subtitle': 'Everything you need to know about our pricing and plans.',
    'pricing.faq.q1': 'How are chat sessions calculated?',
    'pricing.faq.a1': 'A chat session is counted each time a unique user interacts with the chatbot within a 24-hour period, regardless of the number of messages exchanged.',
    'pricing.faq.q2': 'Can I upgrade or downgrade my plan anytime?',
    'pricing.faq.a2': 'Yes - you can switch plans at any time. Upgrades take effect immediately; downgrades apply at the next billing cycle.',
    'pricing.faq.q3': 'Is there a free trial?',
    'pricing.faq.a3': 'Yes - we offer a 14-day free trial for all plans. No credit card required and you can cancel anytime during the trial.',
    'pricing.faq.q4': 'What happens if I exceed my chat session limit?',
    'pricing.faq.a4': 'If you exceed your monthly quota, additional sessions are billed at $0.10 per session. We\'ll notify you when you\'re approaching your limit.',
    
    'pricing.cta.title': 'Ready to get started?',
    'pricing.cta.description': 'Join hundreds of businesses that have already transformed their customer experience with D2 Group. Start your free trial today.',
    'pricing.cta.startTrial': 'Start Free Trial',
    'pricing.cta.contactSales': 'Contact Sales',
    
    // Contact Page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'Ready to transform your customer experience?',
    'contact.hero.description': 'Let\'s start the conversation. Our team of experts is ready to discuss your needs and design the perfect solution.',
    
    'contact.form.title': 'Send us a message',
    'contact.form.subtitle': 'Fill out the information below and we\'ll get back to you within 24 hours',
    'contact.form.name': 'Full Name',
    'contact.form.name.placeholder': 'Enter your full name',
    'contact.form.email': 'Email',
    'contact.form.email.placeholder': 'Enter your email address',
    'contact.form.company': 'Company',
    'contact.form.company.placeholder': 'Enter your company name',
    'contact.form.phone': 'Phone Number',
    'contact.form.phone.placeholder': 'Enter your phone number',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'Select a topic of interest',
    'contact.form.subject.demo': 'Schedule Demo',
    'contact.form.subject.pricing': 'Pricing Consultation',
    'contact.form.subject.support': 'Technical Support',
    'contact.form.subject.partnership': 'Business Partnership',
    'contact.form.subject.other': 'Other',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Share details about your needs or project...',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully! We\'ll get back to you soon.',
    'contact.form.error': 'An error occurred. Please try again later.',
    
    'contact.info.title': 'Contact Information',
    'contact.info.subtitle': 'Multiple ways to connect with us',
    'contact.info.address': 'Address',
    'contact.info.address.detail': '3 Nguyen Co Thach Street, An Loi Dong Ward, Thu Duc City, Ho Chi Minh City',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Business Hours',
    'contact.info.hours.detail': 'Monday - Friday: 8:00 AM - 6:00 PM',
    'contact.info.weekend': 'Saturday - Sunday: 9:00 AM - 5:00 PM',
    'contact.info.response': 'Response Time',
    'contact.info.response.detail': 'Average under 2 hours during business hours',
    
    'contact.demo.title': 'Book a Demo',
    'contact.demo.subtitle': 'See D2 Group in action with a personalized demo',
    'contact.demo.description': 'Schedule a 30-minute demo to explore how AI chatbots can transform your business.',
    'contact.demo.book': 'Book Demo',
    'contact.demo.features': 'Demo includes:',
    'contact.demo.feature1': 'Platform and feature overview',
    'contact.demo.feature2': 'Sample chatbot setup for your industry',
    'contact.demo.feature3': 'Q&A with solution expert',
    'contact.demo.feature4': 'Strategy consultation and implementation roadmap',
    
    'contact.support.title': 'Customer Support',
    'contact.support.subtitle': 'We\'re always here to help you',
    'contact.support.technical': 'Technical Support',
    'contact.support.technical.desc': 'Questions about features and usage',
    'contact.support.billing': 'Billing Support',
    'contact.support.billing.desc': 'Questions about invoices and service plans',
    'contact.support.training': 'Training and Guidance',
    'contact.support.training.desc': 'Learn how to use the platform effectively',
    
    'contact.social.title': 'Connect with us',
    'contact.social.subtitle': 'Follow the latest updates and share experiences',
    
    // Footer
    'footer.company': 'Company',
    'footer.product': 'Product',
    'footer.resources': 'Resources',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.blog': 'Blog',
    'footer.documentation': 'Documentation',
    'footer.apiDocs': 'API Docs',
    'footer.helpCenter': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.security': 'Security',
    'footer.status': 'Status',
    'footer.followUs': 'Follow Us',
    'footer.newsletter.title': 'Subscribe to Newsletter',
    'footer.newsletter.description': 'Get the latest product updates and industry news',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.copyright': '© 2024 D2 Group. All rights reserved.',
    
    // 404 Page
    'notFound.title': 'Page Not Found',
    'notFound.description': 'Sorry, the page you are looking for does not exist or has been moved.',
    'notFound.backHome': 'Back to Home',
    'notFound.contactSupport': 'Contact Support',
    'notFound.errorCode': 'Error code:',
    
    // Form Validation
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email',
    'validation.phone': 'Please enter a valid phone number',
    'validation.minLength': 'Minimum {min} characters',
    'validation.maxLength': 'Maximum {max} characters',
    
    // System Messages
    'system.loading': 'Loading...',
    'system.error': 'An error occurred',
    'system.success': 'Success!',
    'system.tryAgain': 'Try Again',
    'system.cancel': 'Cancel',
    'system.confirm': 'Confirm',
    'system.save': 'Save',
    'system.edit': 'Edit',
    'system.delete': 'Delete',
    'system.view': 'View',
    'system.download': 'Download',
    'system.upload': 'Upload',
    'system.search': 'Search',
    'system.filter': 'Filter',
    'system.sort': 'Sort',
    'system.next': 'Next',
    'system.previous': 'Previous',
    'system.close': 'Close',
    'system.open': 'Open',
    'system.expand': 'Expand',
    'system.collapse': 'Collapse',
    
    // Common terms
    'common.worksWith': 'Works with',
    'common.includes': 'Includes',
    'common.plus': 'Plus',
    'common.per': 'per',
    'common.up': 'Up to',
    'common.from': 'From',
    'common.to': 'To',
    'common.and': 'and',
    'common.or': 'or',
    'common.all': 'All',
    'common.more': 'More',
    'common.less': 'Less',
    'common.new': 'New',
    'common.popular': 'Popular',
    'common.recommended': 'Recommended',
    'common.featured': 'Featured',
    'common.free': 'Free',
    'common.premium': 'Premium',
    'common.pro': 'Pro',
    'common.basic': 'Basic',
    'common.advanced': 'Advanced',
    'common.custom': 'Custom',
    'common.standard': 'Standard',
    'common.enterprise': 'Enterprise',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
