
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'vi';
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.useCases': 'Use Cases',
    'nav.caseStudies': 'Case Studies',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',

    // Pricing page
    'pricing.title': 'Transparent Pricing',
    'pricing.subtitle': 'Choose the perfect plan for your business. No hidden fees, no surprises—just powerful AI chatbot solutions that grow with you.',
    'pricing.freeTrial': '14-day free trial',
    'pricing.noSetupFees': 'No setup fees',
    'pricing.cancelAnytime': 'Cancel anytime',
    'pricing.mostPopular': 'Most Popular',
    'pricing.getStarted': 'Get Started',
    'pricing.contactForPricing': 'Contact for Pricing',
    'pricing.month': '/month',
    'pricing.contactPricing': 'Custom',

    // Pricing plans
    'pricing.starter': 'Starter',
    'pricing.starter.desc': 'Perfect for small businesses starting their automation journey',
    'pricing.growth': 'Growth',
    'pricing.growth.desc': 'Ideal for growing companies with increasing customer volume',
    'pricing.business': 'Business',
    'pricing.business.desc': 'Comprehensive solution for established businesses',
    'pricing.enterprise': 'Enterprise',
    'pricing.enterprise.desc': 'Full-scale solution for large organizations',

    // Features
    'feature.conversations': 'conversations',
    'feature.basicTemplates': 'Basic chatbot templates',
    'feature.websiteIntegration': 'Website widget integration',
    'feature.emailSupport': 'Email support',
    'feature.basicAnalytics': 'Basic analytics dashboard',
    'feature.workflows': 'automated workflows',
    'feature.standardResponse': 'Standard response time',
    'feature.advancedTemplates': 'Advanced chatbot templates',
    'feature.multiChannel': 'Multi-channel integration',
    'feature.crmIntegration': 'CRM integration',
    'feature.advancedAnalytics': 'Advanced analytics & reporting',
    'feature.unlimitedWorkflows': 'Unlimited automated workflows',
    'feature.prioritySupport': 'Priority customer support',
    'feature.abTesting': 'A/B testing capabilities',
    'feature.leadQualification': 'Lead qualification system',
    'feature.customDesign': 'Custom chatbot design',
    'feature.customBranding': 'Custom branding options',
    'feature.priorityResponse': 'Priority response time',
    'feature.unlimited': 'Unlimited',
    'feature.customAI': 'Custom AI model training',
    'feature.dedicatedManager': 'Dedicated account manager',
    'feature.onPremise': 'On-premise deployment',
    'feature.security': 'Enterprise security & compliance',
    'feature.customIntegrations': 'Custom integrations',
    'feature.phoneSupport': '24/7 phone support',
    'feature.slaGuarantees': 'SLA guarantees',
    'feature.whiteLabel': 'White-label solution',
    'feature.advancedReporting': 'Advanced reporting & insights',

    // Features page
    'features.hero.title': 'Powerful Features',
    'features.hero.subtitle': 'Discover how our AI chatbot platform can transform your customer interactions with cutting-edge features designed for modern businesses.',
    'features.hero.stats.implementations': 'Successful Implementations',
    'features.hero.stats.satisfaction': 'Customer Satisfaction',
    'features.hero.stats.uptime': 'Platform Uptime',
    'features.hero.stats.languages': 'Languages Supported',
    'features.coreFeatures.title': 'Core Features',
    'features.coreFeatures.subtitle': 'Everything you need to create exceptional customer experiences',
    'features.intelligentChat.title': 'Intelligent Chat',
    'features.intelligentChat.desc': 'Advanced NLP for natural conversations',
    'features.intelligentChat.details': 'Our AI understands context, intent, and sentiment to provide human-like responses that keep customers engaged.',
    'features.multiChannel.title': 'Multi-Channel Integration',
    'features.multiChannel.desc': 'Seamless integration across all platforms',
    'features.multiChannel.details': 'Deploy your chatbot on websites, WhatsApp, Facebook Messenger, and more with unified conversation management.',
    'features.realTimeAnalytics.title': 'Real-Time Analytics',
    'features.realTimeAnalytics.desc': 'Comprehensive insights and reporting',
    'features.realTimeAnalytics.details': 'Track performance metrics, conversation flows, and customer satisfaction in real-time with detailed dashboards.',
    'features.easyIntegration.title': 'Easy Integration',
    'features.easyIntegration.desc': 'Quick setup with your existing systems',
    'features.easyIntegration.details': 'Connect with your CRM, helpdesk, and business tools through our robust API and pre-built integrations.',
    'features.customization.title': 'Full Customization',
    'features.customization.desc': 'Tailor the experience to your brand',
    'features.customization.details': 'Customize conversation flows, appearance, and responses to match your brand voice and business requirements.',
    'features.support247.title': '24/7 Support',
    'features.support247.desc': 'Round-the-clock assistance',
    'features.support247.details': 'Our expert support team is available 24/7 to help you optimize your chatbot performance and resolve any issues.',
    'features.comparison.title': 'Feature Comparison',
    'features.comparison.subtitle': 'See how our platform compares across different pricing tiers',
    'features.comparison.tableHeaders.feature': 'Feature',
    'features.comparison.tableHeaders.starter': 'Starter',
    'features.comparison.tableHeaders.growth': 'Growth',
    'features.comparison.tableHeaders.business': 'Business',
    'features.comparison.tableHeaders.enterprise': 'Enterprise',
    'features.comparison.coreFeatures': 'Core Features',
    'features.comparison.chatSessions': 'Monthly Chat Sessions',
    'features.comparison.responseTime': 'Average Response Time',
    'features.comparison.analyticsReports': 'Analytics & Reports',
    'features.comparison.customization': 'Customization Level',
    'features.comparison.integrations': 'Integrations & Channels',
    'features.comparison.websiteWidget': 'Website Widget',
    'features.comparison.whatsappBusiness': 'WhatsApp Business',
    'features.comparison.facebookMessenger': 'Facebook Messenger',
    'features.comparison.crmIntegration': 'CRM Integration',
    'features.comparison.apiAccess': 'API Access',
    'features.comparison.support': 'Support & Training',
    'features.comparison.emailSupport': 'Email Support',
    'features.comparison.prioritySupport': 'Priority Support',
    'features.comparison.phoneSupport': 'Phone Support',
    'features.comparison.accountManager': 'Dedicated Account Manager',
    'features.comparison.onboarding': 'Onboarding & Training',
    'features.advancedFeatures.title': 'Advanced Features',
    'features.advancedFeatures.subtitle': 'Take your customer experience to the next level',
    'features.aiTraining.title': 'AI Model Training',
    'features.aiTraining.desc': 'Train your chatbot with your specific business data and industry knowledge for more accurate and relevant responses.',
    'features.workflowAutomation.title': 'Workflow Automation',
    'features.workflowAutomation.desc': 'Create complex automated workflows that handle everything from lead qualification to customer support escalation.',
    'features.sentimentAnalysis.title': 'Sentiment Analysis',
    'features.sentimentAnalysis.desc': 'Understand customer emotions and automatically route conversations to appropriate teams based on sentiment.',
    'features.multilingual.title': 'Multilingual Support',
    'features.multilingual.desc': 'Serve customers in their preferred language with automatic translation and localized responses.',
    'features.liveHandoff.title': 'Live Agent Handoff',
    'features.liveHandoff.desc': 'Seamlessly transfer complex queries to human agents with full conversation context and history.',
    'features.conversationMemory.title': 'Conversation Memory',
    'features.conversationMemory.desc': 'Maintain context across multiple interactions to provide personalized experiences for returning customers.',
    'features.cta.title': 'Ready to Transform Your Customer Experience?',
    'features.cta.subtitle': 'Join thousands of businesses already using our platform to deliver exceptional customer service.',
    'features.cta.startButton': 'Start Free Trial',
    'features.cta.contactButton': 'Contact Sales',
    'features.comparison.values.basic': 'Basic',
    'features.comparison.values.advanced': 'Advanced',
    'features.comparison.values.unlimited': 'Unlimited',
    'features.comparison.values.instant': '< 1 second',
    'features.comparison.values.fast': '< 2 seconds',
    'features.comparison.values.standard': '< 5 seconds',
    'features.comparison.values.full': 'Full',
    'features.comparison.values.limited': 'Limited',

    // Case Studies page
    'caseStudies.hero.title': 'Real Success Stories',
    'caseStudies.hero.subtitle': 'Discover how businesses across industries have transformed their customer experience and achieved remarkable results with D2 Group\'s AI chatbot solutions.',
    'caseStudies.stats.deployments': 'Successful Deployments',
    'caseStudies.stats.conversionIncrease': 'Average Conversion Increase',
    'caseStudies.stats.costReduction': 'Average Cost Reduction',
    'caseStudies.stats.customerSupport': 'Customer Support',
    'caseStudies.labels.challenge': 'Challenge',
    'caseStudies.labels.solution': 'Solution',
    'caseStudies.labels.results': 'Results',
    'caseStudies.industries.title': 'Industries We Serve',
    'caseStudies.industries.subtitle': 'Proven success across diverse business sectors',
    'caseStudies.cta.title': 'Ready to Write Your Success Story?',
    'caseStudies.cta.subtitle': 'Join hundreds of successful businesses that have transformed their customer experience with D2 Group. Let\'s discuss how we can deliver similar results for your organization.',
    'caseStudies.cta.startButton': 'Start Your Success Story',
    'caseStudies.cta.pricingButton': 'View Pricing',

    // Case study details
    'caseStudies.study1.title': 'E-commerce Giant Increases Conversions by 45%',
    'caseStudies.study1.company': 'TechMart Vietnam',
    'caseStudies.study1.industry': 'E-commerce',
    'caseStudies.study1.challenge': 'High cart abandonment rate and overwhelming customer inquiries during peak seasons',
    'caseStudies.study1.solution': 'Deployed AI chatbot for product recommendations, order tracking, and instant customer support',
    'caseStudies.study1.testimonial': 'The chatbot transformed our customer experience. We\'re seeing record-high conversion rates and our support team can focus on complex issues.',
    'caseStudies.study1.author': 'Nguyễn Văn Minh, CEO TechMart Vietnam',

    'caseStudies.study2.title': 'Healthcare Provider Reduces Wait Times by 60%',
    'caseStudies.study2.company': 'MedCare Plus',
    'caseStudies.study2.industry': 'Healthcare',
    'caseStudies.study2.challenge': 'Long patient wait times for appointment booking and basic health inquiries',
    'caseStudies.study2.solution': 'Implemented appointment scheduling bot with symptom checker and health information system',
    'caseStudies.study2.testimonial': 'Our patients love the instant response for appointments and basic health questions. It\'s revolutionized our patient care workflow.',
    'caseStudies.study2.author': 'Dr. Trần Thị Lan, Medical Director',

    'caseStudies.study3.title': 'Financial Services Improves Lead Quality by 80%',
    'caseStudies.study3.company': 'VietFinance Solutions',
    'caseStudies.study3.industry': 'Financial Services',
    'caseStudies.study3.challenge': 'Poor lead qualification process and time-consuming customer onboarding',
    'caseStudies.study3.solution': 'Deployed intelligent lead qualification bot with document processing and KYC automation',
    'caseStudies.study3.testimonial': 'The AI chatbot pre-qualifies leads so well that our sales team only speaks with serious prospects. Our conversion rates have never been higher.',
    'caseStudies.study3.author': 'Lê Hoàng Nam, Sales Director',

    'caseStudies.study4.title': 'Education Platform Boosts Student Engagement by 70%',
    'caseStudies.study4.company': 'EduTech Academy',
    'caseStudies.study4.industry': 'Education',
    'caseStudies.study4.challenge': 'Low student engagement and high drop-out rates in online courses',
    'caseStudies.study4.solution': 'Created AI tutor bot for 24/7 student support, course recommendations, and progress tracking',
    'caseStudies.study4.testimonial': 'Students have a personal AI tutor available 24/7. The improvement in engagement and completion rates has been remarkable.',
    'caseStudies.study4.author': 'Phạm Thị Mai, Academic Director',

    'caseStudies.study5.title': 'Real Estate Agency Generates 3x More Qualified Leads',
    'caseStudies.study5.company': 'PropertyPro Vietnam',
    'caseStudies.study5.industry': 'Real Estate',
    'caseStudies.study5.challenge': 'Difficulty qualifying serious buyers and managing high volume of property inquiries',
    'caseStudies.study5.solution': 'Implemented property search bot with virtual tours and buyer qualification system',
    'caseStudies.study5.testimonial': 'The chatbot pre-qualifies buyers and schedules viewings automatically. Our agents now spend time with serious buyers only.',
    'caseStudies.study5.author': 'Vũ Minh Tuấn, Managing Director',

    'caseStudies.study6.title': 'Hotel Chain Achieves 90% Booking Automation',
    'caseStudies.study6.company': 'Luxury Resorts Group',
    'caseStudies.study6.industry': 'Hospitality',
    'caseStudies.study6.challenge': 'Manual booking process overwhelming staff during peak tourism seasons',
    'caseStudies.study6.solution': 'Deployed booking automation bot with room recommendations and guest service features',
    'caseStudies.study6.testimonial': 'Guests can book rooms, request services, and get recommendations instantly. Our occupancy rates have reached all-time highs.',
    'caseStudies.study6.author': 'Nguyễn Thị Hoa, Operations Manager',

    // Metrics
    'caseStudies.metrics.conversionRate': 'Conversion Rate',
    'caseStudies.metrics.cartAbandonment': 'Cart Abandonment',
    'caseStudies.metrics.responseTime': 'Response Time',
    'caseStudies.metrics.customerSatisfaction': 'Customer Satisfaction',
    'caseStudies.metrics.waitTimes': 'Wait Times',
    'caseStudies.metrics.appointmentBookings': 'Appointment Bookings',
    'caseStudies.metrics.staffEfficiency': 'Staff Efficiency',
    'caseStudies.metrics.patientSatisfaction': 'Patient Satisfaction',
    'caseStudies.metrics.leadQuality': 'Lead Quality',
    'caseStudies.metrics.onboardingTime': 'Onboarding Time',
    'caseStudies.metrics.processEfficiency': 'Process Efficiency',
    'caseStudies.metrics.studentEngagement': 'Student Engagement',
    'caseStudies.metrics.courseCompletion': 'Course Completion',
    'caseStudies.metrics.supportQueries': 'Support Queries',
    'caseStudies.metrics.studentSatisfaction': 'Student Satisfaction',
    'caseStudies.metrics.qualifiedLeads': 'Qualified Leads',
    'caseStudies.metrics.propertyViews': 'Property Views',
    'caseStudies.metrics.salesCycle': 'Sales Cycle',
    'caseStudies.metrics.agentProductivity': 'Agent Productivity',
    'caseStudies.metrics.bookingAutomation': 'Booking Automation',
    'caseStudies.metrics.staffWorkload': 'Staff Workload',
    'caseStudies.metrics.bookingConversion': 'Booking Conversion',
    'caseStudies.metrics.guestSatisfaction': 'Guest Satisfaction',

    // Industries
    'caseStudies.industries.ecommerce': 'E-commerce',
    'caseStudies.industries.ecommerceMetric': '+45% Sales',
    'caseStudies.industries.healthcare': 'Healthcare',
    'caseStudies.industries.healthcareMetric': '-60% Wait Time',
    'caseStudies.industries.finance': 'Finance',
    'caseStudies.industries.financeMetric': '+80% Lead Quality',
    'caseStudies.industries.education': 'Education',
    'caseStudies.industries.educationMetric': '+70% Engagement',
    'caseStudies.industries.realEstate': 'Real Estate',
    'caseStudies.industries.realEstateMetric': '+300% Leads',
    'caseStudies.industries.hospitality': 'Hospitality',
    'caseStudies.industries.hospitalityMetric': '90% Automation',
    'caseStudies.industries.retail': 'Retail',
    'caseStudies.industries.retailMetric': '+35% Conversion',
    'caseStudies.industries.automotive': 'Automotive',
    'caseStudies.industries.automotiveMetric': '+50% Efficiency',
    'caseStudies.industries.insurance': 'Insurance',
    'caseStudies.industries.insuranceMetric': '+25% Claims',
    'caseStudies.industries.manufacturing': 'Manufacturing',
    'caseStudies.industries.manufacturingMetric': '+40% Support',
    'caseStudies.industries.travel': 'Travel',
    'caseStudies.industries.travelMetric': '+55% Bookings',
    'caseStudies.industries.logistics': 'Logistics',
    'caseStudies.industries.logisticsMetric': '+30% Tracking',

    // Contact page
    'contact.hero.title': 'Get in Touch',
    'contact.hero.subtitle': 'Ready to transform your customer conversations? Let\'s discuss how D2 Group can help you achieve your automation goals. Our experts are standing by to provide personalized guidance.',
    'contact.hero.features.consultation.title': 'Free Consultation',
    'contact.hero.features.consultation.desc': 'Expert guidance tailored to your needs',
    'contact.hero.features.response.title': '24-Hour Response',
    'contact.hero.features.response.desc': 'Quick turnaround on all inquiries',
    'contact.hero.features.implementation.title': 'Fast Implementation',
    'contact.hero.features.implementation.desc': 'Go live in as little as 48 hours',
    'contact.form.title': 'Let\'s Start the Conversation',
    'contact.form.subtitle': 'Fill out the form below and our team will reach out to you within 24 hours.',
    'contact.form.fields.name': 'Full Name',
    'contact.form.fields.email': 'Email Address',
    'contact.form.fields.phone': 'Phone Number',
    'contact.form.fields.company': 'Company Name',
    'contact.form.fields.interest': 'Area of Interest',
    'contact.form.fields.message': 'Message',
    'contact.form.placeholders.name': 'John Smith',
    'contact.form.placeholders.email': 'john@company.com',
    'contact.form.placeholders.phone': '+1 (555) 123-4567',
    'contact.form.placeholders.company': 'Acme Corporation',
    'contact.form.placeholders.interest': 'What can we help you with?',
    'contact.form.placeholders.message': 'Tell us about your business needs, current challenges, or any specific questions you have...',
    'contact.form.options.demo': 'Schedule a Product Demo',
    'contact.form.options.pricing': 'Get Pricing Information',
    'contact.form.options.integration': 'Discuss Integration Options',
    'contact.form.options.enterprise': 'Enterprise Solutions',
    'contact.form.options.support': 'Technical Support',
    'contact.form.options.partnership': 'Partnership Opportunities',
    'contact.form.options.other': 'Other',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.privacy': 'By submitting this form, you agree to our Privacy Policy and Terms of Service.',
    'contact.info.title': 'Contact Information',
    'contact.info.email.title': 'Email',
    'contact.info.phone.title': 'Phone',
    'contact.info.address.title': 'Address',
    'contact.info.address.street': 'No. 3 Nguyễn Cơ Thạch Street',
    'contact.info.address.ward': 'An Lợi Đông Ward, Thủ Đức City',
    'contact.info.address.city': 'Ho Chi Minh City, Vietnam',
    'contact.info.hours.title': 'Business Hours',
    'contact.info.hours.weekday': 'Monday - Friday: 9:00 AM - 6:00 PM (GMT+7)',
    'contact.info.hours.saturday': 'Saturday: 10:00 AM - 2:00 PM (GMT+7)',
    'contact.info.hours.emergency': 'Emergency support: 24/7',
    'contact.map.title': 'Find Us',
    'contact.thanks.title': 'Thank You for Your Interest!',
    'contact.thanks.subtitle': 'Your message has been received and our team will respond within 24 hours. In the meantime, feel free to connect with us on social media.',
    'contact.toast.successTitle': 'Thank you for your inquiry!',
    'contact.toast.successDesc': 'We\'ll get back to you within 24 hours. Check your email for confirmation.',
    'contact.toast.errorTitle': 'Oops! Something went wrong',
    'contact.toast.errorDesc': 'Unable to submit form. Please try again or contact us directly via email.',

    // Pricing specific
    'pricing.hero.title': 'Transparent Pricing',
    'pricing.hero.subtitle': 'Choose the perfect plan for your business. No hidden fees, no surprises—just powerful AI chatbot solutions that grow with you.',
    'pricing.hero.features.freeTrial': '14-day free trial',
    'pricing.hero.features.noSetupFees': 'No setup fees',
    'pricing.hero.features.cancelAnytime': 'Cancel anytime',
    'pricing.plans.starter.name': 'Starter',
    'pricing.plans.starter.period': ' VND/month',
    'pricing.plans.starter.desc': 'Perfect for small businesses starting their automation journey',
    'pricing.plans.starter.features.conversations': '1,000 conversations',
    'pricing.plans.starter.features.basicTemplates': 'Basic chatbot templates',
    'pricing.plans.starter.features.websiteIntegration': 'Website widget integration',
    'pricing.plans.starter.features.emailSupport': 'Email support',
    'pricing.plans.starter.features.basicAnalytics': 'Basic analytics dashboard',
    'pricing.plans.starter.features.workflows': '5 automated workflows',
    'pricing.plans.starter.features.standardResponse': 'Standard response time',
    'pricing.plans.growth.name': 'Growth',
    'pricing.plans.growth.period': ' VND/month',
    'pricing.plans.growth.desc': 'Ideal for growing companies with increasing customer volume',
    'pricing.plans.growth.features.conversations': '5,000 conversations',
    'pricing.plans.growth.features.advancedTemplates': 'Advanced chatbot templates',
    'pricing.plans.growth.features.multiChannel': 'Multi-channel integration',
    'pricing.plans.growth.features.crmIntegration': 'CRM integration',
    'pricing.plans.growth.features.advancedAnalytics': 'Advanced analytics & reporting',
    'pricing.plans.growth.features.unlimitedWorkflows': 'Unlimited automated workflows',
    'pricing.plans.growth.features.prioritySupport': 'Priority customer support',
    'pricing.plans.growth.features.abTesting': 'A/B testing capabilities',
    'pricing.plans.growth.features.leadQualification': 'Lead qualification system',
    'pricing.plans.business.name': 'Business',
    'pricing.plans.business.period': ' VND/month',
    'pricing.plans.business.desc': 'Comprehensive solution for established businesses',
    'pricing.plans.business.features.conversations': '15,000 conversations',
    'pricing.plans.business.features.customDesign': 'Custom chatbot design',
    'pricing.plans.business.features.multiChannel': 'Multi-channel integration',
    'pricing.plans.business.features.crmIntegration': 'CRM integration',
    'pricing.plans.business.features.advancedAnalytics': 'Advanced analytics & reporting',
    'pricing.plans.business.features.unlimitedWorkflows': 'Unlimited automated workflows',
    'pricing.plans.business.features.prioritySupport': 'Priority customer support',
    'pricing.plans.business.features.abTesting': 'A/B testing capabilities',
    'pricing.plans.business.features.leadQualification': 'Lead qualification system',
    'pricing.plans.business.features.customBranding': 'Custom branding options',
    'pricing.plans.business.features.priorityResponse': 'Priority response time',
    'pricing.plans.enterprise.name': 'Enterprise',
    'pricing.plans.enterprise.price': 'Custom',
    'pricing.plans.enterprise.period': '',
    'pricing.plans.enterprise.desc': 'Full-scale solution for large organizations',
    'pricing.plans.enterprise.features.unlimited': 'Unlimited conversations',
    'pricing.plans.enterprise.features.customAI': 'Custom AI model training',
    'pricing.plans.enterprise.features.dedicatedManager': 'Dedicated account manager',
    'pricing.plans.enterprise.features.onPremise': 'On-premise deployment option',
    'pricing.plans.enterprise.features.security': 'Enterprise security & compliance',
    'pricing.plans.enterprise.features.customIntegrations': 'Custom integrations',
    'pricing.plans.enterprise.features.phoneSupport': '24/7 phone support',
    'pricing.plans.enterprise.features.slaGuarantees': 'SLA guarantees',
    'pricing.plans.enterprise.features.whiteLabel': 'White-label solution',
    'pricing.plans.enterprise.features.advancedReporting': 'Advanced reporting & insights',
    'pricing.comparison.title': 'Pricing Comparison',
    'pricing.comparison.subtitle': 'Compare all features across our pricing plans.',
    'pricing.comparison.tableHeaders.features': 'Features',
    'pricing.comparison.coreFeatures': 'Core Features',
    'pricing.comparison.channelsIntegrations': 'Channels & Integrations',
    'pricing.comparison.features.monthlySessions': 'Monthly Chat Sessions',
    'pricing.comparison.features.chatbotTemplate': 'Chatbot Template',
    'pricing.comparison.features.responseTime': 'Response Time SLA',
    'pricing.comparison.features.analyticsDashboard': 'Analytics Dashboard',
    'pricing.comparison.features.websiteWidget': 'Website Widget Integration',
    'pricing.comparison.features.whatsapp': 'WhatsApp Business',
    'pricing.comparison.features.messenger': 'Facebook Messenger',
    'pricing.comparison.features.crmIntegration': 'CRM Integration',
    'pricing.comparison.features.customAPI': 'Custom API Access',
    'pricing.comparison.unlimited': 'Unlimited',
    'pricing.comparison.basic': 'Basic',
    'pricing.comparison.advanced': 'Advanced',
    'pricing.comparison.custom': 'Custom',
    'pricing.comparison.fullyCustom': 'Fully Custom',
    'pricing.comparison.standard': 'Standard',
    'pricing.comparison.priority': 'Priority',
    'pricing.comparison.instant': 'Instant',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.subtitle': 'Everything you need to know about our pricing and service packages.',
    'pricing.faq.sessions.question': 'How are chat sessions counted?',
    'pricing.faq.sessions.answer': 'A chat session is counted each time a unique user interacts with your chatbot within a 24-hour window, regardless of the number of messages exchanged.',
    'pricing.faq.upgrade.question': 'Can I upgrade or downgrade my plan at any time?',
    'pricing.faq.upgrade.answer': 'Yes—you can switch plans whenever you like. Upgrades take effect immediately; downgrades apply on your next billing cycle.',
    'pricing.faq.trial.question': 'Is there a free trial available?',
    'pricing.faq.trial.answer': 'Yes—we offer a 14-day free trial on all plans. No credit card required, and you can cancel at any time during the trial.',
    'pricing.faq.exceed.question': 'What happens if I exceed my chat session limit?',
    'pricing.faq.exceed.answer': 'If you go over your monthly quota, additional sessions are billed at VND 3,000 per session. We\'ll send you a notification as you approach your limit.',
    'pricing.cta.title': 'Ready to Get Started?',
    'pricing.cta.subtitle': 'Start your free trial today and discover how D2 Group\'s AI chatbots can transform your customer conversations. No credit card required—cancel anytime.',
    'pricing.cta.startTrial': 'Start Your Free Trial',
    'pricing.cta.contactSales': 'Contact Sales',
    'pricing.cta.helpText': 'Have questions? Our sales team is ready to help you choose the right plan.'
  },
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.features': 'Tính năng',
    'nav.pricing': 'Bảng giá',
    'nav.about': 'Giới thiệu',
    'nav.services': 'Dịch vụ',
    'nav.useCases': 'Trường hợp sử dụng',
    'nav.caseStudies': 'Nghiên cứu trường hợp',
    'nav.contact': 'Liên hệ',
    'nav.getStarted': 'Bắt đầu',

    // Pricing page
    'pricing.title': 'Bảng Giá Minh Bạch',
    'pricing.subtitle': 'Chọn gói hoàn hảo cho doanh nghiệp của bạn. Không có phí ẩn, không có bất ngờ—chỉ là giải pháp chatbot AI mạnh mẽ phát triển cùng bạn.',
    'pricing.freeTrial': 'Dùng thử 14 ngày miễn phí',
    'pricing.noSetupFees': 'Không phí thiết lập',
    'pricing.cancelAnytime': 'Hủy bất cứ lúc nào',
    'pricing.mostPopular': 'Phổ biến nhất',
    'pricing.getStarted': 'Bắt đầu',
    'pricing.contactForPricing': 'Liên hệ để biết giá',
    'pricing.month': '/tháng',
    'pricing.contactPricing': 'Tùy chỉnh',

    // Pricing plans
    'pricing.starter': 'Khởi động',
    'pricing.starter.desc': 'Hoàn hảo cho các doanh nghiệp nhỏ bắt đầu hành trình tự động hóa',
    'pricing.growth': 'Phát triển',
    'pricing.growth.desc': 'Lý tưởng cho các công ty đang phát triển với lượng khách hàng ngày càng tăng',
    'pricing.business': 'Doanh nghiệp',
    'pricing.business.desc': 'Giải pháp toàn diện cho các doanh nghiệp đã thành lập',
    'pricing.enterprise': 'Tập đoàn',
    'pricing.enterprise.desc': 'Giải pháp quy mô lớn cho các tổ chức lớn',

    // Features
    'feature.conversations': 'cuộc trò chuyện',
    'feature.basicTemplates': 'Mẫu chatbot cơ bản',
    'feature.websiteIntegration': 'Tích hợp widget website',
    'feature.emailSupport': 'Hỗ trợ qua email',
    'feature.basicAnalytics': 'Bảng điều khiển phân tích cơ bản',
    'feature.workflows': 'quy trình tự động',
    'feature.standardResponse': 'Thời gian phản hồi tiêu chuẩn',
    'feature.advancedTemplates': 'Mẫu chatbot nâng cao',
    'feature.multiChannel': 'Tích hợp đa kênh',
    'feature.crmIntegration': 'Tích hợp CRM',
    'feature.advancedAnalytics': 'Phân tích & báo cáo nâng cao',
    'feature.unlimitedWorkflows': 'Quy trình tự động không giới hạn',
    'feature.prioritySupport': 'Hỗ trợ khách hàng ưu tiên',
    'feature.abTesting': 'Khả năng kiểm thử A/B',
    'feature.leadQualification': 'Hệ thống đánh giá khách hàng tiềm năng',
    'feature.customDesign': 'Thiết kế chatbot tùy chỉnh',
    'feature.customBranding': 'Tùy chọn thương hiệu tùy chỉnh',
    'feature.priorityResponse': 'Thời gian phản hồi ưu tiên',
    'feature.unlimited': 'Không giới hạn',
    'feature.customAI': 'Đào tạo mô hình AI tùy chỉnh',
    'feature.dedicatedManager': 'Quản lý tài khoản chuyên biệt',
    'feature.onPremise': 'Tùy chọn triển khai tại chỗ',
    'feature.security': 'Bảo mật & tuân thủ cấp doanh nghiệp',
    'feature.customIntegrations': 'Tích hợp tùy chỉnh',
    'feature.phoneSupport': 'Hỗ trợ qua điện thoại 24/7',
    'feature.slaGuarantees': 'Cam kết SLA',
    'feature.whiteLabel': 'Giải pháp white-label',
    'feature.advancedReporting': 'Báo cáo & thông tin chi tiết nâng cao',

    // Features page
    'features.hero.title': 'Tính Năng Mạnh Mẽ',
    'features.hero.subtitle': 'Khám phá cách nền tảng chatbot AI của chúng tôi có thể biến đổi tương tác khách hàng của bạn với các tính năng tiên tiến được thiết kế cho doanh nghiệp hiện đại.',
    'features.hero.stats.implementations': 'Triển khai thành công',
    'features.hero.stats.satisfaction': 'Sự hài lòng của khách hàng',
    'features.hero.stats.uptime': 'Thời gian hoạt động nền tảng',
    'features.hero.stats.languages': 'Ngôn ngữ được hỗ trợ',
    'features.coreFeatures.title': 'Tính Năng Cốt Lõi',
    'features.coreFeatures.subtitle': 'Mọi thứ bạn cần để tạo ra trải nghiệm khách hàng đặc biệt',
    'features.intelligentChat.title': 'Trò Chuyện Thông Minh',
    'features.intelligentChat.desc': 'NLP tiên tiến cho cuộc trò chuyện tự nhiên',
    'features.intelligentChat.details': 'AI của chúng tôi hiểu bối cảnh, ý định và cảm xúc để cung cấp phản hồi giống con người giữ cho khách hàng luôn tham gia.',
    'features.multiChannel.title': 'Tích Hợp Đa Kênh',
    'features.multiChannel.desc': 'Tích hợp liền mạch trên tất cả các nền tảng',
    'features.multiChannel.details': 'Triển khai chatbot của bạn trên website, WhatsApp, Facebook Messenger và nhiều hơn nữa với quản lý cuộc trò chuyện thống nhất.',
    'features.realTimeAnalytics.title': 'Phân Tích Thời Gian Thực',
    'features.realTimeAnalytics.desc': 'Thông tin chi tiết và báo cáo toàn diện',
    'features.realTimeAnalytics.details': 'Theo dõi các chỉ số hiệu suất, luồng cuộc trò chuyện và sự hài lòng của khách hàng trong thời gian thực với bảng điều khiển chi tiết.',
    'features.easyIntegration.title': 'Tích Hợp Dễ Dàng',
    'features.easyIntegration.desc': 'Thiết lập nhanh với hệ thống hiện tại của bạn',
    'features.easyIntegration.details': 'Kết nối với CRM, helpdesk và công cụ kinh doanh của bạn thông qua API mạnh mẽ và tích hợp được xây dựng sẵn.',
    'features.customization.title': 'Tùy Chỉnh Hoàn Toàn',
    'features.customization.desc': 'Điều chỉnh trải nghiệm theo thương hiệu của bạn',
    'features.customization.details': 'Tùy chỉnh luồng cuộc trò chuyện, giao diện và phản hồi để phù hợp với giọng điệu thương hiệu và yêu cầu kinh doanh của bạn.',
    'features.support247.title': 'Hỗ Trợ 24/7',
    'features.support247.desc': 'Hỗ trợ suốt ngày đêm',
    'features.support247.details': 'Đội ngũ hỗ trợ chuyên gia của chúng tôi có sẵn 24/7 để giúp bạn tối ưu hóa hiệu suất chatbot và giải quyết mọi vấn đề.',
    'features.comparison.title': 'So Sánh Tính Năng',
    'features.comparison.subtitle': 'Xem cách nền tảng của chúng tôi so sánh trên các tầng giá khác nhau',
    'features.comparison.tableHeaders.feature': 'Tính năng',
    'features.comparison.tableHeaders.starter': 'Khởi động',
    'features.comparison.tableHeaders.growth': 'Phát triển',
    'features.comparison.tableHeaders.business': 'Doanh nghiệp',
    'features.comparison.tableHeaders.enterprise': 'Tập đoàn',
    'features.comparison.coreFeatures': 'Tính Năng Cốt Lõi',
    'features.comparison.chatSessions': 'Phiên Trò Chuyện Hàng Tháng',
    'features.comparison.responseTime': 'Thời Gian Phản Hồi Trung Bình',
    'features.comparison.analyticsReports': 'Phân Tích & Báo Cáo',
    'features.comparison.customization': 'Mức Độ Tùy Chỉnh',
    'features.comparison.integrations': 'Tích Hợp & Kênh',
    'features.comparison.websiteWidget': 'Widget Website',
    'features.comparison.whatsappBusiness': 'WhatsApp Business',
    'features.comparison.facebookMessenger': 'Facebook Messenger',
    'features.comparison.crmIntegration': 'Tích Hợp CRM',
    'features.comparison.apiAccess': 'Truy Cập API',
    'features.comparison.support': 'Hỗ Trợ & Đào Tạo',
    'features.comparison.emailSupport': 'Hỗ Trợ Email',
    'features.comparison.prioritySupport': 'Hỗ Trợ Ưu Tiên',
    'features.comparison.phoneSupport': 'Hỗ Trợ Điện Thoại',
    'features.comparison.accountManager': 'Quản Lý Tài Khoản Chuyên Biệt',
    'features.comparison.onboarding': 'Onboarding & Đào Tạo',
    'features.advancedFeatures.title': 'Tính Năng Nâng Cao',
    'features.advancedFeatures.subtitle': 'Đưa trải nghiệm khách hàng của bạn lên một tầm cao mới',
    'features.aiTraining.title': 'Đào Tạo Mô Hình AI',
    'features.aiTraining.desc': 'Đào tạo chatbot của bạn với dữ liệu kinh doanh cụ thể và kiến thức ngành để có phản hồi chính xác và phù hợp hơn.',
    'features.workflowAutomation.title': 'Tự Động Hóa Quy Trình',
    'features.workflowAutomation.desc': 'Tạo các quy trình tự động phức tạp xử lý mọi thứ từ đánh giá khách hàng tiềm năng đến leo thang hỗ trợ khách hàng.',
    'features.sentimentAnalysis.title': 'Phân Tích Cảm Xúc',
    'features.sentimentAnalysis.desc': 'Hiểu cảm xúc khách hàng và tự động chuyển cuộc trò chuyện đến các nhóm phù hợp dựa trên cảm xúc.',
    'features.multilingual.title': 'Hỗ Trợ Đa Ngôn Ngữ',
    'features.multilingual.desc': 'Phục vụ khách hàng bằng ngôn ngữ ưa thích của họ với dịch thuật tự động và phản hồi được bản địa hóa.',
    'features.liveHandoff.title': 'Chuyển Giao Tác Viên Trực Tiếp',
    'features.liveHandoff.desc': 'Chuyển giao liền mạch các truy vấn phức tạp cho tác viên con người với bối cảnh và lịch sử cuộc trò chuyện đầy đủ.',
    'features.conversationMemory.title': 'Bộ Nhớ Cuộc Trò Chuyện',
    'features.conversationMemory.desc': 'Duy trì bối cảnh qua nhiều tương tác để cung cấp trải nghiệm cá nhân hóa cho khách hàng quay lại.',
    'features.cta.title': 'Sẵn Sàng Biến Đổi Trải Nghiệm Khách Hàng?',
    'features.cta.subtitle': 'Tham gia cùng hàng nghìn doanh nghiệp đã sử dụng nền tảng của chúng tôi để cung cấp dịch vụ khách hàng đặc biệt.',
    'features.cta.startButton': 'Bắt Đầu Dùng Thử Miễn Phí',
    'features.cta.contactButton': 'Liên Hệ Bán Hàng',
    'features.comparison.values.basic': 'Cơ bản',
    'features.comparison.values.advanced': 'Nâng cao',
    'features.comparison.values.unlimited': 'Không giới hạn',
    'features.comparison.values.instant': '< 1 giây',
    'features.comparison.values.fast': '< 2 giây',
    'features.comparison.values.standard': '< 5 giây',
    'features.comparison.values.full': 'Đầy đủ',
    'features.comparison.values.limited': 'Hạn chế',

    // Case Studies page
    'caseStudies.hero.title': 'Câu Chuyện Thành Công Thực Tế',
    'caseStudies.hero.subtitle': 'Khám phá cách các doanh nghiệp trong nhiều ngành đã biến đổi trải nghiệm khách hàng và đạt được kết quả đáng kể với giải pháp chatbot AI của D2 Group.',
    'caseStudies.stats.deployments': 'Triển Khai Thành Công',
    'caseStudies.stats.conversionIncrease': 'Mức Tăng Chuyển Đổi Trung Bình',
    'caseStudies.stats.costReduction': 'Giảm Chi Phí Trung Bình',
    'caseStudies.stats.customerSupport': 'Hỗ Trợ Khách Hàng',
    'caseStudies.labels.challenge': 'Thách thức',
    'caseStudies.labels.solution': 'Giải pháp',
    'caseStudies.labels.results': 'Kết quả',
    'caseStudies.industries.title': 'Các Ngành Chúng Tôi Phục Vụ',
    'caseStudies.industries.subtitle': 'Thành công đã được chứng minh trong các lĩnh vực kinh doanh đa dạng',
    'caseStudies.cta.title': 'Sẵn Sàng Viết Câu Chuyện Thành Công?',
    'caseStudies.cta.subtitle': 'Tham gia cùng hàng trăm doanh nghiệp thành công đã biến đổi trải nghiệm khách hàng với D2 Group. Hãy thảo luận về cách chúng tôi có thể mang lại kết quả tương tự cho tổ chức của bạn.',
    'caseStudies.cta.startButton': 'Bắt Đầu Câu Chuyện Thành Công',
    'caseStudies.cta.pricingButton': 'Xem Bảng Giá',

    // Case study details
    'caseStudies.study1.title': 'Gã Khổng Lồ Thương Mại Điện Tử Tăng Chuyển Đổi 45%',
    'caseStudies.study1.company': 'TechMart Vietnam',
    'caseStudies.study1.industry': 'Thương mại điện tử',
    'caseStudies.study1.challenge': 'Tỷ lệ bỏ giỏ hàng cao và lượng truy vấn khách hàng áp đảo trong mùa cao điểm',
    'caseStudies.study1.solution': 'Triển khai chatbot AI cho đề xuất sản phẩm, theo dõi đơn hàng và hỗ trợ khách hàng tức thì',
    'caseStudies.study1.testimonial': 'Chatbot đã biến đổi trải nghiệm khách hàng của chúng tôi. Chúng tôi đang thấy tỷ lệ chuyển đổi kỷ lục và đội hỗ trợ có thể tập trung vào các vấn đề phức tạp.',
    'caseStudies.study1.author': 'Nguyễn Văn Minh, CEO TechMart Vietnam',

    'caseStudies.study2.title': 'Nhà Cung Cấp Y Tế Giảm Thời Gian Chờ 60%',
    'caseStudies.study2.company': 'MedCare Plus',
    'caseStudies.study2.industry': 'Y tế',
    'caseStudies.study2.challenge': 'Thời gian chờ bệnh nhân dài để đặt lịch hẹn và các câu hỏi sức khỏe cơ bản',
    'caseStudies.study2.solution': 'Triển khai bot đặt lịch hẹn với kiểm tra triệu chứng và hệ thống thông tin sức khỏe',
    'caseStudies.study2.testimonial': 'Bệnh nhân của chúng tôi yêu thích phản hồi tức thì cho các cuộc hẹn và câu hỏi sức khỏe cơ bản. Nó đã cách mạng hóa quy trình chăm sóc bệnh nhân của chúng tôi.',
    'caseStudies.study2.author': 'BS. Trần Thị Lan, Giám đốc Y khoa',

    'caseStudies.study3.title': 'Dịch Vụ Tài Chính Cải Thiện Chất Lượng Khách Hàng Tiềm Năng 80%',
    'caseStudies.study3.company': 'VietFinance Solutions',
    'caseStudies.study3.industry': 'Dịch vụ tài chính',
    'caseStudies.study3.challenge': 'Quy trình đánh giá khách hàng tiềm năng kém và onboarding khách hàng tốn thời gian',
    'caseStudies.study3.solution': 'Triển khai bot đánh giá khách hàng tiềm năng thông minh với xử lý tài liệu và tự động hóa KYC',
    'caseStudies.study3.testimonial': 'Chatbot AI đánh giá trước khách hàng tiềm năng rất tốt đến nỗi đội bán hàng chỉ nói chuyện với những khách hàng tiềm năng nghiêm túc. Tỷ lệ chuyển đổi của chúng tôi chưa bao giờ cao như vậy.',
    'caseStudies.study3.author': 'Lê Hoàng Nam, Giám đốc Bán hàng',

    'caseStudies.study4.title': 'Nền Tảng Giáo Dục Tăng Sự Tham Gia Học Sinh 70%',
    'caseStudies.study4.company': 'EduTech Academy',
    'caseStudies.study4.industry': 'Giáo dục',
    'caseStudies.study4.challenge': 'Sự tham gia của học sinh thấp và tỷ lệ bỏ học cao trong các khóa học trực tuyến',
    'caseStudies.study4.solution': 'Tạo bot gia sư AI cho hỗ trợ học sinh 24/7, đề xuất khóa học và theo dõi tiến độ',
    'caseStudies.study4.testimonial': 'Học sinh có một gia sư AI cá nhân có sẵn 24/7. Sự cải thiện trong tham gia và tỷ lệ hoàn thành thật đáng chú ý.',
    'caseStudies.study4.author': 'Phạm Thị Mai, Giám đốc Học thuật',

    'caseStudies.study5.title': 'Đại Lý Bất Động Sản Tạo Ra Gấp 3 Lần Khách Hàng Tiềm Năng Có Chất Lượng',
    'caseStudies.study5.company': 'PropertyPro Vietnam',
    'caseStudies.study5.industry': 'Bất động sản',
    'caseStudies.study5.challenge': 'Khó khăn trong việc đánh giá người mua nghiêm túc và quản lý khối lượng lớn truy vấn bất động sản',
    'caseStudies.study5.solution': 'Triển khai bot tìm kiếm bất động sản với tour ảo và hệ thống đánh giá người mua',
    'caseStudies.study5.testimonial': 'Chatbot đánh giá trước người mua và lên lịch xem nhà tự động. Các đại lý của chúng tôi giờ chỉ dành thời gian với những người mua nghiêm túc.',
    'caseStudies.study5.author': 'Vũ Minh Tuấn, Giám đốc Điều hành',

    'caseStudies.study6.title': 'Chuỗi Khách Sạn Đạt 90% Tự Động Hóa Đặt Phòng',
    'caseStudies.study6.company': 'Luxury Resorts Group',
    'caseStudies.study6.industry': 'Khách sạn',
    'caseStudies.study6.challenge': 'Quy trình đặt phòng thủ công làm quá tải nhân viên trong mùa du lịch cao điểm',
    'caseStudies.study6.solution': 'Triển khai bot tự động hóa đặt phòng với đề xuất phòng và tính năng dịch vụ khách',
    'caseStudies.study6.testimonial': 'Khách có thể đặt phòng, yêu cầu dịch vụ và nhận đề xuất ngay lập tức. Tỷ lệ lấp đầy của chúng tôi đã đạt mức cao nhất mọi thời đại.',
    'caseStudies.study6.author': 'Nguyễn Thị Hoa, Quản lý Vận hành',

    // Metrics
    'caseStudies.metrics.conversionRate': 'Tỷ lệ chuyển đổi',
    'caseStudies.metrics.cartAbandonment': 'Bỏ giỏ hàng',
    'caseStudies.metrics.responseTime': 'Thời gian phản hồi',
    'caseStudies.metrics.customerSatisfaction': 'Sự hài lòng khách hàng',
    'caseStudies.metrics.waitTimes': 'Thời gian chờ',
    'caseStudies.metrics.appointmentBookings': 'Đặt lịch hẹn',
    'caseStudies.metrics.staffEfficiency': 'Hiệu quả nhân viên',
    'caseStudies.metrics.patientSatisfaction': 'Sự hài lòng bệnh nhân',
    'caseStudies.metrics.leadQuality': 'Chất lượng khách hàng tiềm năng',
    'caseStudies.metrics.onboardingTime': 'Thời gian onboarding',
    'caseStudies.metrics.processEfficiency': 'Hiệu quả quy trình',
    'caseStudies.metrics.studentEngagement': 'Sự tham gia học sinh',
    'caseStudies.metrics.courseCompletion': 'Hoàn thành khóa học',
    'caseStudies.metrics.supportQueries': 'Truy vấn hỗ trợ',
    'caseStudies.metrics.studentSatisfaction': 'Sự hài lòng học sinh',
    'caseStudies.metrics.qualifiedLeads': 'Khách hàng tiềm năng có chất lượng',
    'caseStudies.metrics.propertyViews': 'Lượt xem bất động sản',
    'caseStudies.metrics.salesCycle': 'Chu kỳ bán hàng',
    'caseStudies.metrics.agentProductivity': 'Năng suất đại lý',
    'caseStudies.metrics.bookingAutomation': 'Tự động hóa đặt phòng',
    'caseStudies.metrics.staffWorkload': 'Khối lượng công việc nhân viên',
    'caseStudies.metrics.bookingConversion': 'Chuyển đổi đặt phòng',
    'caseStudies.metrics.guestSatisfaction': 'Sự hài lòng khách',

    // Industries
    'caseStudies.industries.ecommerce': 'Thương mại điện tử',
    'caseStudies.industries.ecommerceMetric': '+45% Doanh số',
    'caseStudies.industries.healthcare': 'Y tế',
    'caseStudies.industries.healthcareMetric': '-60% Thời gian chờ',
    'caseStudies.industries.finance': 'Tài chính',
    'caseStudies.industries.financeMetric': '+80% Chất lượng khách hàng tiềm năng',
    'caseStudies.industries.education': 'Giáo dục',
    'caseStudies.industries.educationMetric': '+70% Tương tác',
    'caseStudies.industries.realEstate': 'Bất động sản',
    'caseStudies.industries.realEstateMetric': '+300% Khách hàng tiềm năng',
    'caseStudies.industries.hospitality': 'Khách sạn',
    'caseStudies.industries.hospitalityMetric': '90% Tự động hóa',
    'caseStudies.industries.retail': 'Bán lẻ',
    'caseStudies.industries.retailMetric': '+35% Chuyển đổi',
    'caseStudies.industries.automotive': 'Ô tô',
    'caseStudies.industries.automotiveMetric': '+50% Hiệu quả',
    'caseStudies.industries.insurance': 'Bảo hiểm',
    'caseStudies.industries.insuranceMetric': '+25% Khiếu nại',
    'caseStudies.industries.manufacturing': 'Sản xuất',
    'caseStudies.industries.manufacturingMetric': '+40% Hỗ trợ',
    'caseStudies.industries.travel': 'Du lịch',
    'caseStudies.industries.travelMetric': '+55% Đặt chỗ',
    'caseStudies.industries.logistics': 'Logistics',
    'caseStudies.industries.logisticsMetric': '+30% Theo dõi',

    // Contact page
    'contact.hero.title': 'Liên Hệ',
    'contact.hero.subtitle': 'Sẵn sàng biến đổi cuộc trò chuyện khách hàng của bạn? Hãy thảo luận về cách D2 Group có thể giúp bạn đạt được mục tiêu tự động hóa. Các chuyên gia của chúng tôi đang sẵn sàng cung cấp hướng dẫn cá nhân hóa.',
    'contact.hero.features.consultation.title': 'Tư vấn miễn phí',
    'contact.hero.features.consultation.desc': 'Hướng dẫn chuyên gia phù hợp với nhu cầu của bạn',
    'contact.hero.features.response.title': 'Phản hồi trong 24 giờ',
    'contact.hero.features.response.desc': 'Xử lý nhanh chóng mọi yêu cầu',
    'contact.hero.features.implementation.title': 'Triển khai nhanh',
    'contact.hero.features.implementation.desc': 'Đi vào hoạt động chỉ trong 48 giờ',
    'contact.form.title': 'Hãy Bắt Đầu Cuộc Trò Chuyện',
    'contact.form.subtitle': 'Điền vào biểu mẫu dưới đây và đội ngũ của chúng tôi sẽ liên hệ với bạn trong vòng 24 giờ.',
    'contact.form.fields.name': 'Họ và tên',
    'contact.form.fields.email': 'Địa chỉ email',
    'contact.form.fields.phone': 'Số điện thoại',
    'contact.form.fields.company': 'Tên công ty',
    'contact.form.fields.interest': 'Lĩnh vực quan tâm',
    'contact.form.fields.message': 'Tin nhắn',
    'contact.form.placeholders.name': 'Nguyễn Văn A',
    'contact.form.placeholders.email': 'nguyenvana@congty.com',
    'contact.form.placeholders.phone': '+84 909 123 456',
    'contact.form.placeholders.company': 'Công ty ABC',
    'contact.form.placeholders.interest': 'Chúng tôi có thể giúp gì cho bạn?',
    'contact.form.placeholders.message': 'Hãy cho chúng tôi biết về nhu cầu kinh doanh, thách thức hiện tại hoặc bất kỳ câu hỏi cụ thể nào bạn có...',
    'contact.form.options.demo': 'Lên lịch demo sản phẩm',
    'contact.form.options.pricing': 'Nhận thông tin giá',
    'contact.form.options.integration': 'Thảo luận tùy chọn tích hợp',
    'contact.form.options.enterprise': 'Giải pháp doanh nghiệp',
    'contact.form.options.support': 'Hỗ trợ kỹ thuật',
    'contact.form.options.partnership': 'Cơ hội hợp tác',
    'contact.form.options.other': 'Khác',
    'contact.form.submit': 'Gửi tin nhắn',
    'contact.form.sending': 'Đang gửi...',
    'contact.form.privacy': 'Bằng cách gửi biểu mẫu này, bạn đồng ý với Chính sách Bảo mật và Điều khoản Dịch vụ của chúng tôi.',
    'contact.info.title': 'Thông Tin Liên Hệ',
    'contact.info.email.title': 'Email',
    'contact.info.phone.title': 'Điện thoại',
    'contact.info.address.title': 'Địa chỉ',
    'contact.info.address.street': 'Số 3 đường Nguyễn Cơ Thạch',
    'contact.info.address.ward': 'Phường An Lợi Đông, Thành phố Thủ Đức',
    'contact.info.address.city': 'Thành phố Hồ Chí Minh, Việt Nam',
    'contact.info.hours.title': 'Giờ làm việc',
    'contact.info.hours.weekday': 'Thứ Hai - Thứ Sáu: 9:00 - 18:00 (GMT+7)',
    'contact.info.hours.saturday': 'Thứ Bảy: 10:00 - 14:00 (GMT+7)',
    'contact.info.hours.emergency': 'Hỗ trợ khẩn cấp: 24/7',
    'contact.map.title': 'Tìm Chúng Tôi',
    'contact.thanks.title': 'Cảm Ơn Sự Quan Tâm!',
    'contact.thanks.subtitle': 'Tin nhắn của bạn đã được nhận và đội ngũ của chúng tôi sẽ phản hồi trong vòng 24 giờ. Trong thời gian chờ đợi, hãy kết nối với chúng tôi trên mạng xã hội.',
    'contact.toast.successTitle': 'Cảm ơn bạn đã yêu cầu!',
    'contact.toast.successDesc': 'Chúng tôi sẽ liên hệ lại với bạn trong vòng 24 giờ. Hãy kiểm tra email để xác nhận.',
    'contact.toast.errorTitle': 'Ôi! Có gì đó không đúng',
    'contact.toast.errorDesc': 'Không thể gửi biểu mẫu. Vui lòng thử lại hoặc liên hệ trực tiếp qua email.',

    // Pricing specific
    'pricing.hero.title': 'Bảng Giá Minh Bạch',
    'pricing.hero.subtitle': 'Chọn gói hoàn hảo cho doanh nghiệp của bạn. Không có phí ẩn, không có bất ngờ—chỉ là giải pháp chatbot AI mạnh mẽ phát triển cùng bạn.',
    'pricing.hero.features.freeTrial': 'Dùng thử 14 ngày miễn phí',
    'pricing.hero.features.noSetupFees': 'Không phí thiết lập',
    'pricing.hero.features.cancelAnytime': 'Hủy bất cứ lúc nào',
    'pricing.plans.starter.name': 'Khởi động',
    'pricing.plans.starter.period': ' VND/tháng',
    'pricing.plans.starter.desc': 'Hoàn hảo cho các doanh nghiệp nhỏ bắt đầu hành trình tự động hóa',
    'pricing.plans.starter.features.conversations': '1.000 cuộc trò chuyện',
    'pricing.plans.starter.features.basicTemplates': 'Mẫu chatbot cơ bản',
    'pricing.plans.starter.features.websiteIntegration': 'Tích hợp widget website',
    'pricing.plans.starter.features.emailSupport': 'Hỗ trợ qua email',
    'pricing.plans.starter.features.basicAnalytics': 'Bảng điều khiển phân tích cơ bản',
    'pricing.plans.starter.features.workflows': '5 quy trình tự động',
    'pricing.plans.starter.features.standardResponse': 'Thời gian phản hồi tiêu chuẩn',
    'pricing.plans.growth.name': 'Phát triển',
    'pricing.plans.growth.period': ' VND/tháng',
    'pricing.plans.growth.desc': 'Lý tưởng cho các công ty đang phát triển với lượng khách hàng ngày càng tăng',
    'pricing.plans.growth.features.conversations': '5.000 cuộc trò chuyện',
    'pricing.plans.growth.features.advancedTemplates': 'Mẫu chatbot nâng cao',
    'pricing.plans.growth.features.multiChannel': 'Tích hợp đa kênh',
    'pricing.plans.growth.features.crmIntegration': 'Tích hợp CRM',
    'pricing.plans.growth.features.advancedAnalytics': 'Phân tích & báo cáo nâng cao',
    'pricing.plans.growth.features.unlimitedWorkflows': 'Quy trình tự động không giới hạn',
    'pricing.plans.growth.features.prioritySupport': 'Hỗ trợ khách hàng ưu tiên',
    'pricing.plans.growth.features.abTesting': 'Khả năng kiểm thử A/B',
    'pricing.plans.growth.features.leadQualification': 'Hệ thống đánh giá khách hàng tiềm năng',
    'pricing.plans.business.name': 'Doanh nghiệp',
    'pricing.plans.business.period': ' VND/tháng',
    'pricing.plans.business.desc': 'Giải pháp toàn diện cho các doanh nghiệp đã thành lập',
    'pricing.plans.business.features.conversations': '15.000 cuộc trò chuyện',
    'pricing.plans.business.features.customDesign': 'Thiết kế chatbot tùy chỉnh',
    'pricing.plans.business.features.multiChannel': 'Tích hợp đa kênh',
    'pricing.plans.business.features.crmIntegration': 'Tích hợp CRM',
    'pricing.plans.business.features.advancedAnalytics': 'Phân tích & báo cáo nâng cao',
    'pricing.plans.business.features.unlimitedWorkflows': 'Quy trình tự động không giới hạn',
    'pricing.plans.business.features.prioritySupport': 'Hỗ trợ khách hàng ưu tiên',
    'pricing.plans.business.features.abTesting': 'Khả năng kiểm thử A/B',
    'pricing.plans.business.features.leadQualification': 'Hệ thống đánh giá khách hàng tiềm năng',
    'pricing.plans.business.features.customBranding': 'Tùy chọn thương hiệu tùy chỉnh',
    'pricing.plans.business.features.priorityResponse': 'Thời gian phản hồi ưu tiên',
    'pricing.plans.enterprise.name': 'Tập đoàn',
    'pricing.plans.enterprise.price': 'Tùy chỉnh',
    'pricing.plans.enterprise.period': '',
    'pricing.plans.enterprise.desc': 'Giải pháp quy mô lớn cho các tổ chức lớn',
    'pricing.plans.enterprise.features.unlimited': 'Cuộc trò chuyện không giới hạn',
    'pricing.plans.enterprise.features.customAI': 'Đào tạo mô hình AI tùy chỉnh',
    'pricing.plans.enterprise.features.dedicatedManager': 'Quản lý tài khoản chuyên biệt',
    'pricing.plans.enterprise.features.onPremise': 'Tùy chọn triển khai tại chỗ',
    'pricing.plans.enterprise.features.security': 'Bảo mật & tuân thủ cấp doanh nghiệp',
    'pricing.plans.enterprise.features.customIntegrations': 'Tích hợp tùy chỉnh',
    'pricing.plans.enterprise.features.phoneSupport': 'Hỗ trợ qua điện thoại 24/7',
    'pricing.plans.enterprise.features.slaGuarantees': 'Cam kết SLA',
    'pricing.plans.enterprise.features.whiteLabel': 'Giải pháp white-label',
    'pricing.plans.enterprise.features.advancedReporting': 'Báo cáo & thông tin chi tiết nâng cao',
    'pricing.comparison.title': 'So Sánh Bảng Giá',
    'pricing.comparison.subtitle': 'So sánh tất cả tính năng trên các gói giá của chúng tôi.',
    'pricing.comparison.tableHeaders.features': 'Tính năng',
    'pricing.comparison.coreFeatures': 'Tính Năng Cốt Lõi',
    'pricing.comparison.channelsIntegrations': 'Kênh & Tích Hợp',
    'pricing.comparison.features.monthlySessions': 'Phiên Trò Chuyện Hàng Tháng',
    'pricing.comparison.features.chatbotTemplate': 'Mẫu Chatbot',
    'pricing.comparison.features.responseTime': 'SLA Thời Gian Phản Hồi',
    'pricing.comparison.features.analyticsDashboard': 'Bảng Điều Khiển Phân Tích',
    'pricing.comparison.features.websiteWidget': 'Tích Hợp Widget Website',
    'pricing.comparison.features.whatsapp': 'WhatsApp Business',
    'pricing.comparison.features.messenger': 'Facebook Messenger',
    'pricing.comparison.features.crmIntegration': 'Tích Hợp CRM',
    'pricing.comparison.features.customAPI': 'Truy Cập API Tùy Chỉnh',
    'pricing.comparison.unlimited': 'Không giới hạn',
    'pricing.comparison.basic': 'Cơ bản',
    'pricing.comparison.advanced': 'Nâng cao',
    'pricing.comparison.custom': 'Tùy chỉnh',
    'pricing.comparison.fullyCustom': 'Tùy chỉnh hoàn toàn',
    'pricing.comparison.standard': 'Tiêu chuẩn',
    'pricing.comparison.priority': 'Ưu tiên',
    'pricing.comparison.instant': 'Tức thì',
    'pricing.faq.title': 'Câu Hỏi Thường Gặp',
    'pricing.faq.subtitle': 'Mọi thứ bạn cần biết về giá cả và các gói dịch vụ của chúng tôi.',
    'pricing.faq.sessions.question': 'Phiên trò chuyện được tính như thế nào?',
    'pricing.faq.sessions.answer': 'Một phiên trò chuyện được tính mỗi khi người dùng duy nhất tương tác với chatbot của bạn trong cửa sổ 24 giờ, bất kể số lượng tin nhắn được trao đổi.',
    'pricing.faq.upgrade.question': 'Tôi có thể nâng cấp hoặc hạ cấp gói bất cứ lúc nào không?',
    'pricing.faq.upgrade.answer': 'Có—bạn có thể chuyển đổi gói bất cứ lúc nào. Nâng cấp có hiệu lực ngay lập tức; hạ cấp áp dụng vào chu kỳ thanh toán tiếp theo.',
    'pricing.faq.trial.question': 'Có dùng thử miễn phí không?',
    'pricing.faq.trial.answer': 'Có—chúng tôi cung cấp dùng thử miễn phí 14 ngày cho tất cả các gói. Không cần thẻ tín dụng và bạn có thể hủy bất cứ lúc nào trong thời gian dùng thử.',
    'pricing.faq.exceed.question': 'Điều gì xảy ra nếu tôi vượt quá giới hạn phiên trò chuyện?',
    'pricing.faq.exceed.answer': 'Nếu bạn vượt quá hạn ngạch hàng tháng, các phiên bổ sung sẽ được tính với giá 3.000 VND mỗi phiên. Chúng tôi sẽ gửi thông báo khi bạn gần đạt giới hạn.',
    'pricing.cta.title': 'Sẵn Sàng Bắt Đầu?',
    'pricing.cta.subtitle': 'Bắt đầu dùng thử miễn phí ngay hôm nay và khám phá cách chatbot AI của D2 Group có thể biến đổi cuộc trò chuyện khách hàng của bạn. Không cần thẻ tín dụng—hủy bất cứ lúc nào.',
    'pricing.cta.startTrial': 'Bắt Đầu Dùng Thử Miễn Phí',
    'pricing.cta.contactSales': 'Liên Hệ Bán Hàng',
    'pricing.cta.helpText': 'Có câu hỏi? Đội ngũ bán hàng của chúng tôi sẵn sàng giúp bạn chọn gói phù hợp.'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'vi'>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'vi' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
